### ISSUE TITLE
Any plans for JAssimp animation support?

### ISSUE THREAD

**Issue by Ekuju** [assimp/assimp#1039]
Curious if animation is on the road map for the java binding of assimp.

Thanks!

**Comment by kimkulling** [comment]
Do you habe a links to the specification fot them? Would be useful for an
estimation.

Trent Davies <notifications@github.com> schrieb am Di., 18. Okt. 2016,
00:03:

**Comment by Sailsman63** [comment]
I think @TrentWDB meant the generic jassimp binding - JNI/java representation of assimp data structures. Users would still need to build a translation to their specific scene graph format.

**Comment by kimkulling** [comment]
These datastructures are currently not supported?

**Comment by TrentWDB** [comment]
My understanding is that while assimp supports mesh animation, the Java port of assimp does not yet provide a way to access this information.

From the jassimp readme:
"* no support for mesh animations"
https://github.com/assimp/assimp/blob/master/port/jassimp/README

**Comment by Sailsman63** [comment]
That's my understanding as well. I'm working on a project that is going to use jassimp, so I've been reading through the code. I'd be glad to collaborate to help finish the binding, and to add export support. (Very important for my use case) I must warn you, though, I've never actually done any C, C++, or JNI. I'd be working with a reference in one hand.

**Comment by elect86** [comment]
@Sailsman63 Might you be interested in collaborating on a full [java port](https://github.com/java-graphics/assimp)?

**Comment by Sailsman63** [comment]
@elect86 Thanks for the offer. I think that you mentioned that on the jME forum once? I'm going to pass for the moment. I suspect that once you have the main work done, there will always be a scramble to duplicate updates to assimp itself, and sorting out any java-only bugs that crop up. I think that, for my project, setting up native bindings will require less maintenance in the long run.

**Comment by elect86** [comment]
Animations supported via assbin, if interested

**Comment by gynt** [comment]
Any update on this? @Sailsman63 did you try to finish the bindings?

**Comment by Sailsman63** [comment]
No, I've gotten distracted by other projects. I've done a little poking at this, including a very shallow spike trying to make use of a binding built with JavaCPP (could not get the native binary to load, even though I built with their standard script)

Making use of Assimp is still on my radar, but I'm having troubles because I have basically zero experience with JNI/native bindings.

**Comment by TrentWDB** [comment]
@gynt It's been a while since I've looked at this library at all, so my memory is a little fuzzy.

As I went on with my project I remember realizing that the library exposed a lot more animation information than I originally thought. I'm pretty sure it exposes enough bone animation information to implement animations. However it was really really poorly documented. I'm pretty sure I had to read the assimp docs to figure out what was going on, and even then it was not very clear.

I just briefly tried looking for my old code where I was messing around with the animation data and I couldn't find it. :(

**Comment by elect86** [comment]
In the meanwhile I found some time to finish to port the collada importer.

I started testing now using every mesh I find under `/models/collada`

if you have a specific mesh you would like me to test against, don't hesitate

**Comment by kimkulling** [comment]
Hi, which parts of the animation system needs more documentation? I guess
it would be possible to improve this 😀.

Kim

Giuseppe Barbieri <notifications@github.com> schrieb am Mi., 8. Nov. 2017,
23:39:

**Comment by TrentWDB** [comment]
@kimkulling When I return to America in ~a week I'll see if I can find the project that used the animation since it's probably on my desktop. From that I should be able to figure out what animation stuff I used that was relatively undocumented, but no promises that I'll even find it.

**Comment by elect86** [comment]
`anims_with_full_rotations_between_keys.dae` file has been proven and tested to being loaded properly

animations shall be work out of the box now

**Comment by kimkulling** [comment]
Fine, thanks a lot!
