### ISSUE TITLE
Blend: Expected at least one object with no parent

### ISSUE THREAD

**Issue by fredrik955** [assimp/assimp#1105]
Hi Assimp team,

I tried to import this Blend file: https://storage.googleapis.com/assimp_model_error/Parent_error.blend
But I got this error message:
`BLEND: Expected at least one object with no parent`

I am using the new version of Assimp, Version 3.3 -debug -shared -st (GIT commit dffbda9)

**Comment by kimkulling** [comment]
Thanks for the model, but it is really huge. Do you have a smaller one? I will try to load it to see if I can get a clue.

**Comment by fredrik955** [comment]
Sorry, but I don't have a smaller file with the same problem.
Thanks

**Comment by kimkulling** [comment]
OK, I can reproduce this issue. Thanks for the report!

**Comment by kimkulling** [comment]
I guess I have a base understaning: your model contains only one object with a reference to a parent object, which is not part of the blend-scene. Unfortunately the loader only checks if there is a nullpointer defined for a parent in all objects which are part of the blend-file ( the parent reference is descriped by defining the name of the parent ).
Instead of just checking if there is one nullpointer we need to check if the name of the parent node is defined in the scene ( for instance by using a lookup-table ).

**Comment by kimkulling** [comment]
Ok, I am able to render the foot which is part of the model. But the shoe is missing. I detected also some exceptions, which are also not ok.

**Comment by fredrik955** [comment]
Good to hear about the progress on the model!

**Comment by kimkulling** [comment]
I continued to look into this issue. I saw a lof of exceptions, which were caused by false lookups. The blender fileformat was generated of a couple of blender headers called DNA. This DNA consists of a couple of struct-declarations for a lot of different data types like a mesh, faces, the world etc.
So in this model sometimes the lookup for a special date does not fitt to the struct structure. For instance in a mesh I detected a lookup for a scene, which is not defined there. 

So I guess the error "No element without a parent " is just caused by this erroreous import of the entities in that model.
I checked the source of belnder and the lookup in assimp seems to fitt to the structs defined in Blender. Maybe the offsets used for the import are wrong.

I will continue my work.

**Comment by kimkulling** [comment]
What I have recocnize: the format which was used to load assimp blender dna is based on an older version than the version blender is currently using. Is it possible to use an older version of blender? We need to update our dna in assimp.

**Comment by kimkulling** [comment]
I opened https://github.com/assimp/assimp/issues/1172 to trace this issue.
