### ISSUE TITLE
FBX importer: geometric transformations should not be applied to children

### ISSUE THREAD

**Issue by wmatyjewicz** [assimp/assimp#1127]
(This is  a duplicate of #671 which has been closed unsolved.)

When the Assimp FBX importer encounters a node with a geometric transformation (GeometricTranslation, GeometricRotation or GeometricScaling) it applies the transformation to all the children nodes, while according to the [FBX Developer Help](http://help.autodesk.com/view/FBX/2017/ENU/?guid=__files_GUID_C35D98CB_5148_4B46_82D1_51077D8970EE_htm) it should be applied only to the mesh attached to the node.

**Comment by kimkulling** [comment]
But the node descripes the transformation for the mesh. The aiMesh itself does not have any transformation information. So I do not understand the issue :-).

**Comment by wmatyjewicz** [comment]
Ok, let me explain it in more detail.

Suppose FBX node N has two meshes A and B and a child node M.

In FBX, if N has geometric transformations (GeometricTranslation, GeometricRotation or GeometricScaling) than these transformations have to be applied only to its directly attached meshes A and B, but not to its child node M.

Currently, during FBX import geometric transformations seem to be treated the same as local ones (LocalTranslation, LocalRotation, LocalScaling), so they are applied both to directly attached meshes and all children nodes.

I have a test case for it, but left in on another computer. I'll attach it after the weekend.

**Comment by wmatyjewicz** [comment]
I've attached an example ASCII FBX file with geometric transformations. The file extension has been changed to `.txt` to make GitHub not accept it: [boxes-geometric-xform.txt](https://github.com/assimp/assimp/files/693910/boxes-geometric-xform.txt)

The Box001 node has GeometricRotation and GeometricScaling transformations which should be applied only to its directly attached mesh, and the children node Box002 (and its directly attached mesh) should be left untouched by them.

**Comment by nem0** [comment]
This is an issue for me too, I had to reimplement my importer to use FBX SDK because of this.

**Comment by lamogui** [comment]
In fact the main problem is that the PostRotation is not inverted like mentioned in fbx sdk
http://help.autodesk.com/view/FBX/2017/ENU/?guid=__files_GUID_10CDD63C_79C1_4F2D_BB28_AD2BE65A02ED_htm

That caused me some trouble with lights and cameras when I was working with fbxsdk.

**Comment by rickomax** [comment]
@lamogui, you're sure that this is the issue root?

**Comment by lamogui** [comment]
Pettry sure I wrote my own fbx importer using the official fbx sdk and that's written in the documentation http://help.autodesk.com/view/FBX/2017/ENU/?guid=__files_GUID_10CDD63C_79C1_4F2D_BB28_AD2BE65A02ED_htm

**Comment by lamogui** [comment]
Remaining unkown for me are the scaling offset / pivots which are such a pain to implement when you only whant a position orientation scale as output... I got the correct rotation but never the correct scaling so artist need to remove the scaling pivot in the modeler

**Comment by mesilliac** [comment]
Assimp's FBX import code actually does have a section which is specifically inverting the PostRotation matrix before use.

I'm looking into this and it's problematic because either (a) the geometric transforms get inserted in between the main node and a new node containing each mesh, or (b) the geometric transforms are inverted before attaching child nodes.

With (a) the original node no longer contains any mesh, which is problematic as the node name in FBX seems to be the mesh name. If that node doesn't contain any meshes it would likely cause all sorts of problems in user applications.

With (b) there's a whole bag of worms if the geometric transform is animated.

I think i'll just assume it will never be animated and use (b). From the example FBX file provided by @wmatyjewicz above, the geometric transform is indeed marked as *not* animatable. As geometric transforms are a feature pretty-much specific to 3DS Max, probably this can be vaguely relied on.

**Comment by mesilliac** [comment]
i guess there's a (c) which is to add another node prior to the geometric transforms and make any child nodes the children of that node... but then they are no longer children of the original node.

**Comment by rickomax** [comment]
@mesilliac , I guess (c) is plausible as long the final result be visibly correct.

**Comment by mesilliac** [comment]
I made an initial solution using (b) as it was easier to fit it in that way... if there are problems it should be changed to (c) :)
