### ISSUE TITLE
Build fails with clang-4.0

### ISSUE THREAD

**Issue by yurivict** [assimp/assimp#1141]
Please see the log and details here: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=216160

**Comment by turol** [comment]
https://github.com/assimp/assimp/blob/master/code/D3MFImporter.cpp#L234
This is an obious typo. How the hell did this ever work?

**Comment by kimkulling** [comment]
Fixed!

**Comment by kimkulling** [comment]
Good quedtion, really good question!!!

turol <notifications@github.com> schrieb am Di., 17. Jan. 2017, 16:34:

**Comment by turol** [comment]
I think what happened is that `(xmlReader->getAttributeValue(D3MF::XmlTag::z.c_str()), nullptr)` was interpreted as an application of the comma operator which returned `nullptr`. Then the expression became `ai_strtof > nullptr` which is also valid and evaluates to bool. This was then implicitly convertable to float, making the whole expression well-typed. Then a newer clang failed on the comparison since apparently nullptr was no longer considered the same as a function type.

`vertex.z` would have always been 1.0. Is the testsuite actually hitting this?
