### ISSUE TITLE
OBJ loader hugh numbers abort loading

### ISSUE THREAD

**Issue by Schrompf** [assimp/assimp#1201]
A valid line (albeit senseless) causes the loading to fail, even though the data is actually valid.

vn 0.000000 0.000000 -77654089151094779000000000000.000000

**Comment by kimkulling** [comment]
This normal will cause an overflow, because 77654089151094779000000000000.000000 is not a float as far as I know. We could check against overflows and log a warning. Or we could try to map the value onto a float. But this error will occur in all importers which are using our fast_atof I guess.

Any opinion :-) ?

**Comment by kimkulling** [comment]
The value will not be interpreted as a double as well. An exception will be thrown.

**Comment by kimkulling** [comment]
Fixed by 3d088e5d903d994a7708b5c95312a18072b7e523
