### ISSUE TITLE
PyAssimp ignores `.so.*` files

### ISSUE THREAD

**Issue by MInner** [assimp/assimp#1218]
I had `/lib64/libassimp.so.3` file, but 

```
# ./pyassimp/helper.py
...
215                     if filename.lower().find('assimp')==-1 or\
216                         os.path.splitext(filename)[-1].lower() not in ext_whitelist:
217                         continue
```

only checks against `.so` files. I added a simlink, but that would be great if this check could check for any files that have both `assimp` and `.so` strings somewhere in the filename.

**Comment by kimkulling** [comment]
Ok, I will add this feature I guess. Any hints for good files / names to look for?

**Comment by rspencer01** [comment]
The code actually reads

    # our minimum requirement for candidates is that
    # they should contain 'assimp' somewhere in
    # their name
    if filename.lower().find('assimp')==-1 or\
        os.path.splitext(filename)[-1].lower() not in ext_whitelist:
        continue

The comment is lying.  Due to the slightly confusing way that the if statement works, the requirement is that both the filename contains `assimp` and ends in a whitelisted extension.

As said, we could change the `or` to an `and`, but then we risk trying every single system library.  Alternatives include a regex for the suffix (eg `.so(.*)`), a search anywhere in the string for `.so` or removing the suffix test entirely.

**Comment by kimkulling** [comment]
Should be fixed by https://github.com/assimp/assimp/pull/2035
