### ISSUE TITLE
Android NDK build fails.

### ISSUE THREAD

**Issue by dbrant** [assimp/assimp#1233]
I'm by no means an expert in either cmake or NDK building, so I may be doing something wrong, but no matter what method(s) I've tried, building the project for Android produces the following error:

```
Scanning dependencies of target assimp
[  1%] Building CXX object code/CMakeFiles/assimp.dir/Assimp.cpp.o
[  2%] Building CXX object code/CMakeFiles/assimp.dir/BaseImporter.cpp.o
[  2%] Building CXX object code/CMakeFiles/assimp.dir/BaseProcess.cpp.o
[  3%] Building CXX object code/CMakeFiles/assimp.dir/PostStepRegistry.cpp.o
[  3%] Building CXX object code/CMakeFiles/assimp.dir/ImporterRegistry.cpp.o
[  4%] Building CXX object code/CMakeFiles/assimp.dir/DefaultIOStream.cpp.o
[  5%] Building CXX object code/CMakeFiles/assimp.dir/DefaultIOSystem.cpp.o
[  5%] Building CXX object code/CMakeFiles/assimp.dir/Importer.cpp.o
[  6%] Building CXX object code/CMakeFiles/assimp.dir/SGSpatialSort.cpp.o
[  6%] Building CXX object code/CMakeFiles/assimp.dir/VertexTriangleAdjacency.cpp.o
[  7%] Building CXX object code/CMakeFiles/assimp.dir/SpatialSort.cpp.o
[  7%] Building CXX object code/CMakeFiles/assimp.dir/SceneCombiner.cpp.o
[  8%] Building CXX object code/CMakeFiles/assimp.dir/ScenePreprocessor.cpp.o
[  8%] Building CXX object code/CMakeFiles/assimp.dir/SkeletonMeshBuilder.cpp.o
[  9%] Building CXX object code/CMakeFiles/assimp.dir/SplitByBoneCountProcess.cpp.o
[ 10%] Building CXX object code/CMakeFiles/assimp.dir/StandardShapes.cpp.o
[ 10%] Building CXX object code/CMakeFiles/assimp.dir/TargetAnimation.cpp.o
[ 11%] Building CXX object code/CMakeFiles/assimp.dir/RemoveComments.cpp.o
In file included from E:\git\assimp\code\ParsingUtils.h:49:0,
                 from E:\git\assimp\code\RemoveComments.cpp:46:
E:\git\assimp\code\StringUtils.h: In function 'float ai_strtof(const char*, const char*)':
E:\git\assimp\code\StringUtils.h:100:37: error: '::atof' has not been declared
         val = static_cast< float >( ::atof( begin ) );
                                     ^
E:\git\assimp\code\StringUtils.h:104:37: error: '::atof' has not been declared
         val = static_cast< float >( ::atof( token.c_str() ) );
                                     ^
make[2]: *** [code/CMakeFiles/assimp.dir/RemoveComments.cpp.o] Error 1
make[1]: *** [code/CMakeFiles/assimp.dir/all] Error 2
make: *** [all] Error 2
```

The above was when I tried building it in Windows, but I've also tried in in Linux, and also with different versions of the NDK.

I'm using roughly the following commands:

```
#!/bin/sh

# Points to a standalone Android toolchain
# See https://developer.android.com/ndk/guides/standalone_toolchain.html
# and http://www.myandroidonline.com/2015/06/09/compile-assimp-open-source-library-for-android/
export ANDROID_NDK_TOOLCHAIN=$HOME/android/toolchain-armeabi

# Points to the Android SDK
ANDROID_SDK=$HOME/android/sdk

# This file must be downloaded from the android-cmake project on github:
# https://github.com/taka-no-me/android-cmake](https://github.com/taka-no-me/android-cmake
export ANDTOOLCHAIN=$HOME/android/android-cmake/android.toolchain.cmake

# Do not touch these
export PATH=$PATH:$ANDROID_SDK/tools
export PATH=$PATH:$ANDROID_SDK/platform-tools
export PATH=$PATH:$ANDROID_SDK/android-toolchain/bin

# Add additional args here as appropriate
cmake -DCMAKE_TOOLCHAIN_FILE=$ANDTOOLCHAIN \
      -DANDROID_NDK=$ANDROID_NDK \
      -DCMAKE_BUILD_TYPE=Release \
      -DANDROID_ABI="armeabi-v7a" \
      -DANDROID_NATIVE_API_LEVEL=android-21 \
      -DANDROID_FORCE_ARM_BUILD=TRUE \
      -DCMAKE_INSTALL_PREFIX=install \
      ..

cmake --build .
```

**Comment by xaviergmail** [comment]
I'm new to both CMake and NDK, but I managed to compile this under NDK 14 with support for c++11 using llvm's libc++.

I stumbled across the same blog post as you on the matter, but it seems to be rather outdated!
I'll be covering the steps using a **standalone-ish** toolchain. This means I will be using the CMake and Ninja build tools provided by Android studio, but not the NDK bundle. 
If you want to save on disk space, install everything through Android studio, skip steps 2-6 and update your paths accordingly (You can find everything inside `C:\Users\username\AppData\Local\Android\sdk\ndk-bundle` as well as the toolchain inside `ndk-bundle`.

Here's  what I did (On Windows, sadly..  **Replace &lt;version&gt; with the appropriate strings for your case.**):
1. Everything is assumed to be within a `thirdparty` folder
2. Get the latest NDK release from https://developer.android.com/ndk/downloads/index.html (I happened to be using 14b at the time of writing)
3. Get the latest AssImp release (**Note** I happen to be using the latest commit  ad80f97 in the master branch for convenient CMake options that release 3.3.1 does not have, you'll see later on.)
4. Get the _poorly written_ batch script below. Have a look at it and modify it for your needs.
5. The contents of `thirdparty` should now contain `android-ndk-r<version>`, `assimp-<version>`, `build.assimp.bat`
6. Open a terminal inside `thirdparty` and run the following command. Edit API version for your compatibility needs (I have Pyhton 3 installed): `python android-ndk-r14b/build/tools/make_standalone_toolchain.py --arch=arm --stl=libc++ --api=23 --install-dir=android-toolchain-23-llvm` 
7. Edit the following batch file to correspond to the versions you use. Note that I disable building tests, just check the Travis results. Also I am enabling only specific loaders to minimize the size of the binary. 13MB just for an OBJ loader!? That's insane.

8. Run the batch file and your binary should be in `%OUTPUT_DIR%/code/libassimp.so`

Here is the batch file I use. It makes my eyes bleed, but it works.
**Note** I use Unix-y tools provided by either cygwin or the Git Bash bundle within cmd because I can't be bothered to learn windows-specific commands. Watch out for those if you don't have either installed!
```
@echo off
cls

REM *NOTE* Change these based on 
SET ASSIMP_DIR=assimp-<VERSION>
SET OUTPUT_DIR=assimp-build
SET ANDROID_PATH=C:\Users\<USERNAME>\AppData\Local\Android\sdk
SET NDK_PATH=%~dp0android-ndk-<VERSION>
SET NDK_TOOLCHAIN=%~dp0toolchain-<VERSION>
SET CMAKE_TOOLCHAIN=%NDK_PATH%\build\cmake\android.toolchain.cmake
SET CMAKE_PATH=%ANDROID_PATH%\cmake\<VERSION>

REM *NOTE* Careful if you don't want rm -rf, I use it for testing purposes.
rm -rf %OUTPUT_DIR%
mkdir %OUTPUT_DIR%

REM pushd doesn't seem to work ):<
cd %OUTPUT_DIR%

if not defined ORIGPATH set ORIGPATH=%PATH%
SET PATH=%CMAKE_PATH%\bin;%ANDROID_PATH%\tools;%ANDROID_PATH%\platform-tools;%ORIGPATH%

cmake ^
      -GNinja ^
      -DCMAKE_TOOLCHAIN_FILE=%CMAKE_TOOLCHAIN% ^
      -DASSIMP_ANDROID_JNIIOSYSTEM=ON ^
      -DANDROID_NDK=%NDK_PATH% ^
      -DCMAKE_MAKE_PROGRAM=%CMAKE_PATH%\bin\ninja.exe ^
      -DCMAKE_BUILD_TYPE=Release ^
      -DANDROID_ABI="armeabi-v7a" ^
      -DANDROID_NATIVE_API_LEVEL=23 ^
      -DANDROID_FORCE_ARM_BUILD=TRUE ^
      -DCMAKE_INSTALL_PREFIX=install ^
      -DANDROID_STL=c++_shared ^
      -DANDROID_TOOLCHAIN=clang ^

      -DASSIMP_BUILD_TESTS=OFF ^

      -DASSIMP_BUILD_ALL_IMPORTERS_BY_DEFAULT=OFF ^
      -DASSIMP_BUILD_OBJ_IMPORTER=ON ^

      ../%ASSIMP_DIR%

cmake --build .

cd ..
```


I haven't tested this within my application yet, but at least I have the shared library built which is a good start. I hope someone finds this useful.

Let me know if you run into any issues!

**Comment by dbrant** [comment]
Thanks for that; I'm actually working in Windows too, so I was able to adapt your steps pretty easily, and got it to build.  However, my whole point in wanting to use assimp is to support all the **other** 3d formats besides OBJ.  And when I enabled all the other importers, I got some additional errors, but I was able to fix them by passing an additional flag to the compiler, namely `-Wno-c++11-narrowing`.

So then, when the build completed, I ended up with a .so file with a size of about **75MB** :astonished:. Is that... right?! And that's only for arm-v7a... If I want to bundle a separate library for arm64, that's another 75MB. That's really prohibitive for and Android app. :(

**Comment by xaviergmail** [comment]
Oops! I thought I had mentioned `-Wno-c++11-narrowing` for blend formats and some other for release 3.3.1.
And sadly, I haven't got a clue concerning huge binaries and I am also relatively concerned,
With the following cmake flags (and -O2!), the shared library for arm-v7a is still a whopping 11MB!
```
ASSIMP_BUILD_TESTS=OFF
ASSIMP_NO_EXPORT=ON
ASSIMP_BUILD_ASSIMP_TOOLS=OFF
ASSIMP_BUILD_ALL_IMPORTERS_BY_DEFAULT=OFF
```

I don't know how else to achieve a more lean output, but this really is a killer for mobile apps. Perhaps some project members could shine some light? In another issue, if need be.

**Comment by dbrant** [comment]
The 75MB library does, in fact, work when used from my Android app. However, there's definitely something not right about that huge size.  When I build assimp for Windows as a DLL, even if I statically link the VC++ runtime into it, the final size of the DLL is **3MB**, which is roughly what I would expect. I really hope that there's some kind of flag or option we're missing that would take the Android build down to that size!

**Comment by xaviergmail** [comment]
Eureka! The NDK toolchain retains debug info in built binaries even for the `release` CMake configuration.
The gradle script for building the release APK takes care of stripping debug symbols for us. Magic! 😄 

![apk-analyzer](http://i.imgur.com/lt8ikpR.png)


You could add `-Wl,-s` to the clang options, or manually invoke the strip executable included in the NDK if keeps your mind at ease :)

**Comment by kimkulling** [comment]
75 MB sounds big, I do agree. Release or Debug build?

Kim

**Comment by kimkulling** [comment]
Ah, ok, surprising!

**Comment by dbrant** [comment]
Well dip me in butter and call me a biscuit. Thanks again! The library is now at 5MB with all importers included.  Although I'm still having trouble building it for arm64, but this is enough to get started.

**Comment by kimkulling** [comment]
OK, I will close the issue.

**Comment by rickomax** [comment]
Any tip on this?
![blob](https://cloud.githubusercontent.com/assets/12863984/25769518/d55148b6-31f1-11e7-9812-8de2d74afe05.png)

**Comment by sinigr54** [comment]
Hello, can you help me build assimp for android. My OS is Linux? Step by step. Thanks!
