### ISSUE TITLE
Exporting embedded textures

### ISSUE THREAD

**Issue by leerichard42** [assimp/assimp#1280]
When trying to convert an FBX with embedded textures, it looks like the exported files try to reference the original image file path rather than embedding the image data.

[Example input and output files](https://www.dropbox.com/sh/fxxyn83wtzilw3d/AAB_OxT1naZrwdM1lI5ABnJfa?dl=0)

**Comment by mlavik1** [comment]
According to [the documentation](https://github.com/assimp/assimp/wiki/Embedded-Textures-References)  embedded textures should be referenced like this: "*[TEXTURE_INDEX]" ("*1", "*2", etc.). However, the FBX importer instead references them by filename and relies on the user to call `aiScene::GetEmbeddedTexture`. This is the best way to do it for FBX, since FBX expects embedded textures to have a filename.

So I guess we need to support both these ways of referencing embedded textures? If so, I think we should do what @leerichard42 proposed.
What do you think @kimkulling ?

**Comment by kimkulling** [comment]
Closed by https://github.com/assimp/assimp/pull/2451
