### ISSUE TITLE
Support USD

### ISSUE THREAD

**Issue by kimkulling** [assimp/assimp#1332]
See https://github.com/PixarAnimationStudios/USD/commit/3b6468258e046305726bd0b127160db904442f3e

**Comment by ronpadz** [comment]
I would gladly become a Patron of this project if a commitment were to be made to integrate this capability. Do reach out to me to let me know if you want to take me up on this. Here is a resource that should assist the effort: https://github.com/kcoley/gltf2usd

**Comment by kimkulling** [comment]
Good to know. I guess I need to evaluate the effort.

**Comment by morgan3d** [comment]
USD is the #1 requested format that I encounter.

**Comment by dg0yal** [comment]
This would be great and open a bunch of AR workflows

**Comment by RichardTea** [comment]
We've had requests for this too now. Will try to look into an importer in the coming months.

Unfortunately I won't have the time to write an exporter.
Pixar have made writing a compliant USDz far too complex, apparently because they think every file must be memory-mapped.

They've placed a a lot of surprising (and frankly _utterly insane_) constraints on the ZIP container which add a lot of unexpected exporter complexity, and means it will need its own customised zip library as no common authoring tools can actually do that.

Note:
This means making any edits whatsoever to a USDz file using any generally-available tool (OS built-in, 7z, Winrar, Winzip etc) will corrupt the USDz and strictly-compliant tools will not be able to open them.

I will _not_ enforce any of these constraints when reading. Pixar can go hang - it is not the 1990s, we can use the heap.

**Comment by RichardTea** [comment]
Pixar's USD library is here:
https://github.com/PixarAnimationStudios/USD

It's really quite large, and apparently doesn't currently compile.

**Comment by RichardTea** [comment]
Reading a USD requires mesh subdivision, Pixar have published the OpenSubDiv they use:
https://github.com/PixarAnimationStudios/OpenSubdiv

**Comment by ronpadz** [comment]
I suspect that you'll be able to leverage some of the heavy lifting that Google has already done with their open source converter at https://github.com/google/usd_from_gltf. This is what we now depend upon for our conversions, but we live in a gltf-first world so this is ideal for that purpose.

**Comment by dimitre** [comment]
I've just noticed this effort and thought it can be interesting to link here:
https://github.com/cpichard/usdassimp

**Comment by tellypresence** [comment]
[tinyusdz](https://github.com/syoyo/tinyusdz) might also be worth considering as a basis for investigation:
```
TinyUSDZ is secure, portable and dependency-free(depends only on C++ STL. 
Other 3rd-party libraries included. Yes, you don't need pxrUSD/OpenUSD library!) 
USDZ/USDC/USDA library written in C++14.
```
Note: uses apache license

**Comment by tellypresence** [comment]
Had a look at `tinyusdz` (#5520), promising but not sure it's ready for use by assimp unfortunately.

**Comment by kimkulling** [comment]
Closed by https://github.com/assimp/assimp/pull/5628
