### ISSUE TITLE
Vertex color bug in Collada importer.

### ISSUE THREAD

**Issue by peter5k** [assimp/assimp#1417]
The following happens when loading a DAE file exported from Maya 2017:

The alpha component of the vertex color overwrites the red component, and all vertices will have alpha 1.0 regardless. 

The only workaround was to delete the line: 

&lt;param name="A" type="double"/&gt;
         
from the color accessor to ignore the alpha channel.

[VtxColor_Cube.zip](https://github.com/assimp/assimp/files/1273124/VtxColor_Cube.zip)

**Comment by RaymondKHessel** [comment]
Stumbled over the same problem - seems to be caused by commit 
https://github.com/assimp/assimp/commit/a75eb86af4cfee2d597f734a930642e63c061caf
which modified TReal& aiColor4t<TReal>::operator[](unsigned int i) in color4.inl such that it does not allow accessing the alpha component anymore (instead returns the red component).

That operator is used in ColladaParser.cpp in ColladaParser::ExtractDataObjectFromChannel for the color using i==3 - hence the alpha component always overwrites the red component.

My guess is that the code in color4.inl should read

````
// ------------------------------------------------------------------------------------------------
template <typename TReal>
AI_FORCE_INLINE TReal aiColor4t<TReal>::operator[](unsigned int i) const {
    switch ( i ) {
        case 0:
            return r;
        case 1:
            return g;
        case 2:
            return b;
        case 3:
            return a;
        default:
            break;
    }
    return r;
}
// ------------------------------------------------------------------------------------------------
template <typename TReal>
AI_FORCE_INLINE TReal& aiColor4t<TReal>::operator[](unsigned int i) {
    switch ( i ) {
        case 0:
            return r;
        case 1:
            return g;
        case 2:
            return b;
        case 3:
            return a;
        default:
            break;
    }
    return r;
}
````

**Comment by jsigrist** [comment]
This issue can likely be closed thanks to this PR: https://github.com/assimp/assimp/pull/2441

**Comment by kimkulling** [comment]
Done!
