### ISSUE TITLE
gltf loader is ignoring material properties that are all 1s 

### ISSUE THREAD

**Issue by ptc-meichner** [assimp/assimp#1434]
Is this really expected behavior (according to the gltf specification) ?
code/glTFImporter.cpp, lines 177-180: 

if (col.r != 1.f || col.g != 1.f || col.b != 1.f || col.a != 1.f) {
mat->AddProperty(&col, 1, pKey, type, idx);
}

Thx!

**Comment by dhritzkiv** [comment]
Hi @ptc-meincher. I think the reason for this is because the default material in assimp is white diffuse. 

However, this check is unnecessary, and probably also incorrect, in my opinion, as other colour values (emissive, ambient) may be defined as `1,1,1,1`, but that's not the default colour for those in assimp. Also, the only notion of a default material value in glTF 1.0 spec is a 50% emissive colour.

I'd argue that the `if` statement can be dropped, and the colour can be added to the assimp material each time.

**Comment by ptc-meichner** [comment]
I realized it's an issue, as some models I was loading had materials with perfectly valid specular component (1,1,1,1) which would be skipped during loading.
