### ISSUE TITLE
unable to buid Assimp in android ndk

### ISSUE THREAD

**Issue by ruellm** [assimp/assimp#1513]
i was trying to build Assimp with android NDK and i am getting an error (related to C++ standard library)
environment: Windows using Android NDK

i built the tool chain like this:
`python make_standalone_toolchain.py --arch arm --stl libc++ --api 23 --install-dir android-toolchain-23-llvm`

here is my build batch file (im using windows)
`SET ASSIMP_DIR=assimp
SET OUTPUT_DIR=assimp-build
SET ANDROID_PATH=C:\Users\[my user name]\AppData\Local\Android\Sdk
SET NDK_PATH=C:\Users\[my user name]\AppData\Local\Android\Sdk\ndk-bundle
SET NDK_TOOLCHAIN=thirdparty\android-toolchain-23-llvm
SET CMAKE_TOOLCHAIN=%NDK_PATH%\build\cmake\android.toolchain.cmake
SET CMAKE_PATH=%ANDROID_PATH%\cmake\3.6.4111459

if not defined ORIGPATH set ORIGPATH=%PATH%
SET PATH=%CMAKE_PATH%\bin;%ANDROID_PATH%\tools;%ANDROID_PATH%\platform-tools;%ORIGPATH%

cmake ^
      -GNinja ^
      -DCMAKE_TOOLCHAIN_FILE=%CMAKE_TOOLCHAIN% ^
      -DASSIMP_ANDROID_JNIIOSYSTEM=ON ^
      -DANDROID_NDK=%NDK_PATH% ^
      -DCMAKE_MAKE_PROGRAM=%CMAKE_PATH%\bin\ninja.exe ^
      -DCMAKE_BUILD_TYPE=Release ^
      -DANDROID_ABI="armeabi-v7a" ^
      -DANDROID_NATIVE_API_LEVEL=23 ^
      -DANDROID_FORCE_ARM_BUILD=TRUE ^
      -DCMAKE_INSTALL_PREFIX=install ^
      -DANDROID_TOOLCHAIN=clang ^
	  -DCMAKE_CXX_FLAGS="-Wno-c++11-narrowing -latomic -lstdc++" ^
      -DASSIMP_BUILD_TESTS=OFF ^

      -DASSIMP_BUILD_ALL_IMPORTERS_BY_DEFAULT=OFF ^
      -DASSIMP_BUILD_FBX_IMPORTER=ON ^

      %ASSIMP_DIR%

cmake --build .`

the error i am getting is
`In file included from thirdparty\assimp\port\AndroidJNI\AndroidJNIIOSystem.cpp:59:
C:/Users/username/AppData/Local/Android/Sdk/ndk-bundle/sources/cxx-stl/llvm-libc++/include\fstream:906:13: error: use of undeclared identifier 'fseeko'
        if (fseeko(__file_, -__c, SEEK_CUR))`

In file included from C:/Users/username/AppData/Local/Android/Sdk/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/include\fstream:41:
C:/Users/username/AppData/Local/Android/Sdk/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/include\cstdio:107:11: error: no member named 'fgetpos' in the global namespace
  using ::fgetpos;
        ~~^
C:/Users/username/AppData/Local/Android/Sdk/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/include\cstdio:117:11: error: no member named 'fsetpos' in the global namespace
  using ::fsetpos;
        ~~^
2 errors generated.

it does look like it cant find the fseeko,fgetpos,fsetpos function when fstream is included in AndroidJNIIOSystem.cpp.

any steps i am lacking or things i need to do to find the other C++ standard libraries?

additional info: im using assimp-4.0.1 downloaded thru zip and not cloned from github.

**Comment by kimkulling** [comment]
Hi, because I cannot reporduce the issue here at the moment: could you please try to modify the file 
assimp\port\AndroidJNI\AndroidJNIIOSystem.cpp: replace the 
`#include <stdlib.h>`
by
`#include <fstream>`
I guess the issue will be caused by a definition for fseeko which is expected to be declared in the global scope and the fstream-header is expecting this symbol to be declared in the std-namespace.

Thanks!

**Comment by stevesamknows** [comment]
Sounds like an issue with unified headers.  A few questions:
 * what version of Android NDK are you using (i.e. 15b, 15c, 16 RC1, 16 RC2)
 * which minimum API do you specify in build.gradle?
I have found that due to the new "unified headers", that fseeko may not be available
below API 24 in NDKs newer than 15b -- YMMV, but would suggest experimenting
with different NDK versions and min API levels to see if that makes a difference...

**Comment by ruellm** [comment]
yeah that maybe it, im using the latest android NDK version (r15c)
and the minimum API is 23 and can't go any lower than that since my phone is using Android 6.0.
i have found an alternative and work around of this issue, ill just build Assimp without the default ASSIMP_ANDROID_JNIIOSYSTEM and implement own IOSystem instead of using Assimp's default.
found this tutorial: http://shellblade.net/android-assimp.html
hopefully everything works as expected.

**Comment by stevesamknows** [comment]
Maybe also try setting up an android studio virtual device (e.g. Nexus 5X running API 26) to build against newer APIs without upgrading your phone;)

**Comment by kimkulling** [comment]
And it would be greate to be able to reproduce the issue locally:

`python make_standalone_toolchain.py --arch arm --stl libc++ --api 23 --install-dir android-toolchain-23-llvm`

Where did the tool make_standalone_toolchain.py comes from? I do not have a clue honestly speaking.

I will try to build this config on my VM as well because by build is currently working.

**Comment by ruellm** [comment]
>Where did the tool make_standalone_toolchain.py comes from? I do not have a clue honestly speaking.

make_standalone_toolchain.py is part of Android NDK, and it can be found under build/tools folder, you can download the latest android NDK build at:
https://developer.android.com/ndk/downloads/index.html

and build a toolchain for API level 23https://developer.android.com/ndk/guides/standalone_toolchain.html

**Comment by kimkulling** [comment]
I am currently able to reproduce the issue locally. Stay tuned.

**Comment by kimkulling** [comment]
So I will add your windows batch script as a first step. You need to set the right NDK-version for 64bit. And I found some other compile issues. I will open a WIP-pull-request to start showing you what I did.
