### ISSUE TITLE
Generated CMake config script contains hard-coded values

### ISSUE THREAD

**Issue by mikepurvis** [assimp/assimp#1517]
Here: https://github.com/assimp/assimp/blob/master/assimp-config.cmake.in#L48-L51

This causes problems on OS X where a full path to the installed library seems to be required, see reports like https://github.com/ros-planning/geometric_shapes/issues/23#issuecomment-284830221.

It would be preferred to find the library and headers using `find_library` and `find_path`, similar to what you actually do in your own `Findassimp.cmake`: https://github.com/assimp/assimp/blob/master/cmake-modules/Findassimp.cmake#L55-L65

**Comment by kimkulling** [comment]
OK, thanks for the hint. We will take care!

**Comment by traversaro** [comment]
> It would be preferred to find the library and headers using find_library and find_path, similar to what you actually do in your own Findassimp.cmake: https://github.com/assimp/assimp/blob/master/cmake-modules/Findassimp.cmake#L55-L65 

As the `assimp-config.cmake` file is generated by Assimp itself, there is no need to perform a system-wide search using [`find_library`](https://cmake.org/cmake/help/v3.5/command/find_library.html) and [`find_path`](https://cmake.org/cmake/help/v3.5/command/find_path.html). The typical solution for this problem is to generate a CMake config file that contains imported targets rather than raw library names, see in CMake documentation https://cmake.org/cmake/help/v3.11/manual/cmake-packages.7.html and in particular https://cmake.org/cmake/help/v3.11/manual/cmake-packages.7.html#creating-relocatable-packages .

**Comment by traversaro** [comment]
@kimkulling I would be happy to contribute a fix for this, and it would be definitly easier if we could require CMake at least 2.8.11 for building assimp . If this is not feasible, it would be still possible to support imported targets requiring CMake 2.8.7 .

**Comment by traversaro** [comment]
A solution that requires CMake 2.8.7 is available in https://github.com/assimp/assimp/compare/master...traversaro:cmake_imported_targets . 

Other possible modifications: 
* Requiring CMake would 2.8.8 would permit to substitute the non-relocatable `ASSIMP_ROOT_DIR` with a relocatable version 
* Setting `ASSIMP_LIBRARIES` to `ASSIMP::assimp` would permit to solve several problems related to the exact name of the library generate, such as https://github.com/assimp/assimp/issues/1912 .

**Comment by daef** [comment]
bump

**Comment by traversaro** [comment]
If bumping the `cmake_minimum_required` version to at least 2.8.7 is ok (see https://repology.org/metapackage/cmake/versions for which version of CMake is available in which Linux distributions) I will be happy to open a PR.
