### ISSUE TITLE
Asset importing failes when special characters are part of the uri

### ISSUE THREAD

**Issue by kimkulling** [assimp/assimp#1612]
Try to import an asset in a folder with chinese symbols in it like:

C:\Users\Administrator\AppData\LocalLow\xxx\xxxx\423155567\Assets\海涛\monster.FBX

This will fail. We need file operations to be able to deal with special symbols as well.

**Comment by loebl** [comment]
As far as I know:

On Windows this means either using `char*` with a language-specific locale OR using `wchar_t*` and using UTF16 (and associated `wfstream` classes) independent (more or less) of the selected locale. You might need to extent the interface at that point. For my project I wrote a custom IOSystem class, which translates UTF8 `char*` strings to `wchar_t*` strings (using boost::locale) and used the windows specific `wfopen` function to open files.

As boost isn't part of assimp anymore this is probably not what you want. But utf8cpp also offers a 8 to 16 bit conversion, which should do the same.

On Linux `char*` can be used, as it maps to UTF8, if the locale is set correctly, so UTF-8 file paths work transparently with the existing C-library functions. (That means I do not think a change is necessary; have not tested it)

If you are interested I can modify the default IOSystem and open a pull request with the windows specific changes. The user then has to ensure the `char*` dropped into assimp is UTF8-encoded. Also this problem seems to be related to issue #194

**Comment by mlavik1** [comment]
I'm still having this issue, with a filepath in UTF8 ("D:\Models\UnicodeIssues\テスト.obj").

@kimkulling  in your commit you added `IsTextUnicode` to check if it's Unicode, but in my case it returns 0, even though the filename is UTF8. The [documentation for IsTextUnicode](https://docs.microsoft.com/en-us/windows/desktop/api/winbase/nf-winbase-istextunicode) says that it "is not foolproof".
My questions is: Is it necessary to do that check at all? In UTF8 all the ANSI characters are encoded the same as in ANSI, so handling it as unicode (using `MultiByteToWideChar` and `_wstat64`) should still work when it's not Unicode, right?

By the way, I added a breakpoint and checked the encodings to verify that the filename string is actually UTF8, and it definitely is (テ was represented by e38386 in the string).

**Comment by rmccampbell** [comment]
I looked into this and IsTextUnicode is definitely not the right thing to do here. As far as I can tell from the documentation and experimentation what it really does is detect UTF-16 encoded text (which Microsoft erroneously calls "unicode" despite the fact that unicode is not an encoding). Even for this task it seems to only works with certain combinations of flags: with NULL passed as in the current code, it seems to never return true, and with IS_TEXT_UNICODE_UNICODE_MASK it only detects UTF-16 little-endian with BOM. For detecting UTF-8 it is entirely useless as far as I can tell.

And as @mlavik1 says all ASCII (not ANSI) characters are valid UTF-8 anyway so checking is pointless. You can check after the conversion to see if it failed (use MB_ERR_INVALID_CHARS) and fall back on the legacy encoding but by default you should use the unicode API. 

Is it possible to reopen this or should a new issue be created?

**Comment by jiangcaiyang** [comment]
@rmccampbell Seems your approach does not work on my machine.
![image](https://user-images.githubusercontent.com/2796406/104889901-cc7cad00-59a9-11eb-868a-19fc1e7d6299.png)
The ```bool DefaultIOSystem::Exists(const char *pFile) const``` will return false because the converted path does not exist.

**Comment by rmccampbell** [comment]
You should be converting your strings to UTF-8 first; CP_ACP uses the system default character set which is different depending on your OS settings, and largely obsolete. It also cannot represent all unicode characters unless the default happens to be set to UTF-8 (which is only possible on newer versions of Windows and must be explicitly enabled). The assimp aiString type is also documented as being always UTF-8 [encoded](http://assimp.sourceforge.net/lib_html/structai_string.html), so this should consistent with any internal strings produced by assimp i.e. texture paths (note that this is probably not enforced anywhere so it is very likely that some models will have alternate encodings like Windows 1252 embedded in their material properties; this would have to either fixed in whatever software generated the models or by reencoding the strings in code after loading them).

**Comment by rmccampbell** [comment]
Note that if you have string literals you want to make sure are utf-8 encoded try surrounding them in `u8""`, and check if UTF-8 is set as the default encoding in Visual Studio settings. If you have a string already in another encoding (i.e. in a file) unfortunately the answer is not as simple; there are probably external libraries that can do it easily. Worst case you can use the MultiByteToWideChar and WideCharToMultiByte functions to convert your strings from native encoding to utf-8, and put that in a wrapper function somewhere. But be careful because if those files are moved to a different computer they might break. (I'm guessing from a quick search on Chinese charsets that you're using GBK or similar? Which won't be the default on a non-Chinese computer.)

**Comment by jiangcaiyang** [comment]
My computer is Windows 10, which defaults uses GBK charset. and when I try to convert using command line, Assimp will read a native string which will be GBK, in this case MultiByteToWideChar will use CP_ACP instead of just use CP_UTF8.

**Comment by jiangcaiyang** [comment]
aiString is in fact unfortunately does not have charset conversion functions. It is weaker than other Strings. Take a look at QString, it has many static functions to convert from. It will convert in its implementation. It is usable if Assimp's aiString behaves like QString, or just gain ability to handle different charset's conversions. Internally, QString stores its content in UTF-16 code unit.

**Comment by rmccampbell** [comment]
Yeah that might help. I just remembered you can also use std::filesystem::path if you're using c++17 or higher, which allows conversion between "native" charset and utf-8 or utf-16, plus convenient path manipulation functions.

As for reading command line arguments, I think you can use windows wmain or wWinMain entry point to get command line args as wide chars. Then they can more easily be converted to utf-8, either with std::filesystem or some other library.
I guess Qt also uses the wide char args behind the scenes on windows: see [this](https://stackoverflow.com/questions/4101864/windows-unicode-commandline-argv), which suggests using QApplication::arguments() to get args as QStrings, which can then be easily converted to utf8.

**Comment by jiangcaiyang** [comment]
The fact is, when using default build configuration to build Assimp, Assimp Viewer just can't open any model that contains Chinese character in any part of its path. I started to debug Assimp Viewer, and only to find that it goes to DefaultIOSystem's implementation. Other user may cusrtomize their io system, but as an end-user, the default one is not sufficient.

**Comment by rmccampbell** [comment]
Ah, so there is a bug in Assimp Viewer. I've only tried the programmatic interface. Yes that should absolutely be fixed. I would file a new bug though since the bug is really in the Viewer which is calling DefaultIOSystem.

**Comment by rmccampbell** [comment]
I took a look at the code for that, and unfortunately it is a huge mess of code using legacy ANSI functions instead of unicode, so making it fully unicode aware would be a lot of work. Treating only the command line args as unicode is pretty easy however. Maybe a temporary improvement would be to add a preprocessor define that would disable the unicode calls in DefaultIOSystem and use the ANSI ones instead, and only set this define for the Assimp Viewer. That would solve @jiangcaiyang's problem but only postpone the unicode problem.

**Comment by rmccampbell** [comment]
There might be a much easier way to fix this, but it only works on newer builds of Windows 10. See [this](https://docs.microsoft.com/en-us/windows/uwp/design/globalizing/use-utf8-code-page) way to change the internal "ANSI" codepage for an app to utf-8 using a manifest file. I think that would be pretty simple to add to the build chain and require zero code changes. It wouldn't help older OS users, but it might be the best option.

**Comment by jiangcaiyang** [comment]
![image](https://user-imag@rmccampbell s.githubusercontent.com/2796406/105661229-eb2df700-5f07-11eb-81d2-55eaa5db8f80.png)
@rmccampbell This flag. But we can't assume whether an end-user has this checkbox clicked.

**Comment by rmccampbell** [comment]
I tried adding the manifest file to a simple dummy program and it worked without the global utf-8 option checked as you show (btw your image link is broken). So the end-user doesn't have to have any non-default settings, but they do have to have an up-to-date windows.
