### ISSUE TITLE
mOffsetMatrix is weird...

### ISSUE THREAD

**Issue by TurkeyMan** [assimp/assimp#163]
This is probably not a bug, probably user error, but I can't work out how mOffsetMatrix is produced. It doesn't seem to be what it says it is...
I look at FBXConverter.cpp:1270, it calculates mOffsetMatrix there by, inverse(boneInBindPose) \* nodeMatrix
But if try and do the same thing in my own code, it produces different results.

What I want is the animation in world space.
I transform vertices by their node matrices into world space, and prefer to animate them there. I try and produce my own world-space animation matrices by animationMatrix \*  inverse(boneInBondPose), but the results are wrong.

I've fiddled with this for days. It's never been a problem before when working with my own custom art package exporters. Something very subtle is different here, and I can't work out what it is...

I'd appreciate any ideas, also perhaps a feature added to assimp to support fetching the animation in world space rather than node-local space via the mOffsetMatrix.

**Comment by kimkulling** [comment]
Still there?

**Comment by TurkeyMan** [comment]
Yeah. Never solved this. Moved on.

**Comment by mesilliac** [comment]
I actually recently documented mOffsetMatrix more clearly... the previous documentation was wrong. It should be much more clear now. #1803 

the mOffsetMatrix should always be a transformation from the space of the bone to the space of the mesh. So to get a vertex position in world space, you take the bone transform in world space, multiply by mOffsetMatrix, then apply it to the vertex position in mesh space. This should remain the same no matter how the bone is animated.

It's calculated from the world-space transforms of the bone and mesh in the bind pose. The bone transform is inverted, and this is multiplied by the mesh transform, resulting in a transform from bone space to mesh space, via world space.

**Comment by cjgribel** [comment]
> I actually recently documented mOffsetMatrix more clearly... the previous documentation was wrong. It should be much more clear now. #1803
> 
> the mOffsetMatrix should always be a transformation from the space of the bone to the space of the mesh. So to get a vertex position in world space, you take the bone transform in world space, multiply by mOffsetMatrix, then apply it to the vertex position in mesh space. This should remain the same no matter how the bone is animated.
> 
> It's calculated from the world-space transforms of the bone and mesh in the bind pose. The bone transform is inverted, and this is multiplied by the mesh transform, resulting in a transform from bone space to mesh space, via world space.

I've been able to reconstruct the inverse bind (mOffsetMatrix) as it is described here. One detail that might cause confusion is the mesh transform, which is/seems to be identity in most models. When the mesh transform is identity, it has no effect and mOffsetMatrix is simply the inverse of the bone transform at bind pose. When the mesh transform is _not_ identity however, it will influence mOffsetMatrix:
`mOffsetMatrix = inverse(Bone_global_bindpose) * Mesh_transform`.

As a sidenote, one can wonder what happens when a model has multiple meshes, and they have _different_ mesh transformations. This would imply that one mOffsetMatrix is needed _per mesh_, which is not very intuitive. I have not encountered such a situation, but one could probably be produced in e.g. Maya.

@mesilliac It is stated in #1803 that mOffsetMatrix transforms **bone -> mesh space**. One can argue however that it is the other way around. Consider:
Mesh transform in world space: `M[mesh -> world]`
Global bone transform at bind pose, in world space: `G[bone -> world]`
Then,
`mOffsetMatrix[mesh -> bone] = inverse(G[bone -> world]) * M[mesh -> world]`
Here I've used the right-to-left transformation order convention, i.e. mOffsetMatrix transforms from **mesh** to **bone** via **world**.
I otherwise agree with the description in #1803, for example

> This matrix describes the position of the mesh in the local space of this bone

but, again, this seems rather as a **mesh -> bone** space transformation.

**Comment by mesilliac** [comment]
> @mesilliac It is stated in #1803 that mOffsetMatrix transforms **bone -> mesh space**. One can argue however that it is the other way around. Consider:
> Mesh transform in world space: `M[mesh -> world]`
> Global bone transform at bind pose, in world space: `G[bone -> world]`
> Then,
> `mOffsetMatrix[mesh -> bone] = inverse(G[bone -> world]) * M[mesh -> world]`
> Here I've used the right-to-left transformation order convention, i.e. mOffsetMatrix transforms from **mesh** to **bone** via **world**.
> I otherwise agree with the description in #1803, for example
> 
> > This matrix describes the position of the mesh in the local space of this bone
> 
> but, again, this seems rather as a **mesh -> bone** space transformation.

@cjgribel this depends on what you mean by a "space transformation", which comes down to a conceptual distinction of how one thinks about the transforms. If we imagine that we are transforming _coordinates_, then the order in which you present it is correct, as we are transforming mesh-space coordinates into bone-space coordinates and then finally world-space coordinates. If on the other hand we imagine that we are transforming the _space itself_, then we have a transform from world-space to bone-space to mesh-space ending with a final working space of mesh space.

While matrix arithmetic is usually taught as a method of coordinate transformation, i've found that complex chains of coordinate-system transformation via matrices are much simpler conceptualized as reference-frame transformations, transforming space rather than coordinates. The actual math of course is identical in both cases.

I'm not aware of any accepted terminology to express this distinction in the context of computer graphics. I've seen a lot of confusion caused by it, such as the confusion in this thread. If the terminology exists to express it more clearly, using that appropriately would be best. If i were re-doing it now i would probably discard any mention of "space" and only talk about "coordinates" and "reference frames". I only started using this terminology recently.

The general reason i find space-transformation simpler than coordinate-transformation seems to be that i think of translations as vectors. Thus the translation from the world origin to the mesh origin i consider "world to mesh". However this is _also_ the transformation that converts mesh-space coordinates into world-space coordinates, "mesh to world". Both are equaly valid in general, but the spatial transformation concept matches much better with the vector-based transformation most of us are taught to intuit, making it far more effective for analyzing complex transformation chains, and for constructing transformation matrices in program code. When clarified slightly, the mesh transformation can be expressed both as "world to mesh space" and "mesh to world coordinates", hence the choice of "bone to mesh space" for the mOffsetMatrix. I didn't understand it in quite as much detail when i made the change (i thought it was simply wrong), but this would have been the fundamental reason.

**Comment by cjgribel** [comment]
@mesilliac These are good points and I agree that there is validity in both notations. Yes it's confusing and unfortunate that there isn't a single etsbalished notation when it comes to transformations. Knowing this issue is closed since long I'll refrain from taking the discussion further & instead hope our exchange can help others understand the topic a little bit better.
