### ISSUE TITLE
Tesselation on point cloud

### ISSUE THREAD

**Issue by jonnius** [assimp/assimp#1791]
Is it possible to import a point cloud and let Assimp do the tesselation? If yes, which formats are supported and how can i configure the tesselation?

**Comment by dibenedetto** [comment]
i am not an official contributor (although i contribute from time to time), so this answer is my personal opinion.

assimp is an asset importer/exporter, with a thin layer of processing utilities targeted at getting assets ready for rendering.

what you are asking for is a complex geometry processing tool, known as surface reconstruction from unordered point sets (a.k.a. point clouds). imho, this is not assimp business.

you can find several geometry processing libraries for that and other purposes, google for vcg, igl, or cgal libraries, just to mention some.

m.

**Comment by kimkulling** [comment]
We got this feature request quiet often to be able to import point clouds. And assimp provides some basic mesh tools. Maybe we shall give it a try? Please just vote!

**Comment by dibenedetto** [comment]
i am a computer graphics (CG) researcher and an entrepreneur in that field, so please be aware that my comments are biased by my background.

in CG it is extremely important to be able to handle both:
- point clouds: an unordered set of points;
- meshes; an ordered set of points linked by faces (e.g., with connectivity/topology information);

if the question is: "should assimp import files with vertex-only data and no topology?" then my answer is "definitely yes". i had to bypass assimp in those situations because it failed or gave me an arbitrary meshing.

if the question is: "should assimp generate meshes from a point cloud input?" then my answer is "not now and never ever": this is a tough and open task, researchers on this field are publishing papers every year. assimp should import point cloud and meshes to a common format, by a deterministic processing, and not performing an arbitrary (and painful) 3D reconstruction.

m.

**Comment by ardenpm** [comment]
I would tend to agree that generating meshes from point clouds is somewhat beyond the scope of I would expect AssImp to do for me. However that said I probably wouldn't complain if it was available. More support for tessellation of NURBS, SubD and other B-rep data would be higher on my list, while those can also be complex their techniques are more well established than those for point clouds (and not fundamentally ill-posed to begin with). I don't know to what degree any of those are already supported in AssImp, some of the formats supported have some of these types but I haven't tested them.

However we often find it useful to at least be able to produce tessellated primitive at point locations in a point cloud, for example spheres of a specified size. This can be extremely handy for just viewing and diagnosing point clouds in any rendering platform. Of course that generates a lot of geometry but in many cases that's fine. We usually just script that now but it would be a nice to have.

**Comment by jonnius** [comment]
I know that there is no generic tessellation algorithm. This task highly depends on the point cloud and the requirements. On some point clouds even a human would not be able to decide where to put the faces. But sometimes you might have a clean point cloud  where some well researched approaches give good results. I would not expect Assimp to be the cutting edge tessellation tool and implement all known approaches with tons of parameters to be set...

I fully understand if the developers decide that tessellation is out of scope for Assimp. For me it would be nice to have.

**Comment by JekaS178RUS** [comment]
+1 for import/export of point clouds, and I agree with dibenedetto and ardenpm, mesh generation from points might be tricky and lie out of scope for assimp

**Comment by kimkulling** [comment]
I guess doing all in assimp does not make many sense. Bit we can use the point-cloud-library to compose a workflow.

**Comment by JekaS178RUS** [comment]
@kimkulling it might introduce huge dependency to the project, I belive to leave it is a better option

**Comment by jonnius** [comment]
I see that ASSIMP is a powerful and lightweight library for loading assets and some fundamental, but very useful processing tools. I do agree that tesselation is a complex field and might too much for ASSIMP. Once it is there, people expect the same quality as the rest of ASSIMP has. So probably a bad idea...
