### ISSUE TITLE
Embedded texture loading inconsistency between FBX and GLTF2

### ISSUE THREAD

**Issue by loebl** [assimp/assimp#1838]
I noticed this while digging around texture loading behaviour.

Currently FBX will store embedded textures by their file path, while GLTF 2 (possibly others too, haven't checked) will store them with an asterisk and an index (e.g. `*2`). As far as I know, GLTF 2 has in some cases no other choice, as textures not necessarily need to have a name.

When loading mixed file types, this leads to inconsistent handling of embedded textures.
My proposal: Let GetEmbeddedTexture from aiScene also load embedded textures with an asterisk. (see loebl/assimp@e217358)
An alternative would be to set this texture reference also as file name, so GetEmbeddedTexture does not need to be changed.

**Comment by mlavik1** [comment]
According to [the documentation](https://github.com/assimp/assimp/wiki/Embedded-Textures-References) embedded textures should be referenced like this: "*[TEXTURE_INDEX]" ("*1", "*2", etc.). However, the FBX importer instead references them by filename and relies on the user to call `aiScene::GetEmbeddedTexture`. This is the best way to do it for FBX, since FBX expects embedded textures to have a filename.

So I guess we need to support both these ways of referencing embedded textures? If so, I think we should do what @loebl proposed.
What do you think @kimkulling ?

**Comment by kimkulling** [comment]
Closed by https://github.com/assimp/assimp/pull/2451
