### ISSUE TITLE
Offset matrix is wrong documented

### ISSUE THREAD

**Issue by kimkulling** [assimp/assimp#1950]
https://stackoverflow.com/questions/50143649/what-does-moffsetmatrix-actually-do-in-assimp/50234820#50234820

**Comment by mesilliac** [comment]
it depends how you think of the transform. If the matrix multiplications come after the point (i.e `point * transform` with `point` being a "row" vector) then it makes sense to say it converts from "mesh space to bone space", as it takes a point in mesh space and outputs a point in bone space. But when using matrix premultiplication as assimp does (`tranform * point` with `point` being a "column" vector) it makes more sense to think of it as transforming the space itself, from "bone space to mesh space", whereupon the point in mesh space can be used.

This is why the original poster is confused, because they are thinking about it backwards compared to how assimp treats point transformation. This is probably leading directly to their confusion with working out the transformation matrix of the bone and thinking this should be the same as mOffsetMatrix, when in fact it is the inverse.

This is all especially confusing as DirectX uses postmultiplication, and OpenGL uses premultiplication.

This all said, i hope that someone can update the documentation so that it makes it clear for everybody. It's very difficult to specify clearly without an "official" way of thinking about this sort of thing. I can't even find it documented anywhere how assimp treats transformation matrix multiplication... although the matrix notation used on the "Data Structures" page of the assimp docs impies premultipliction with column vectors.
