### ISSUE TITLE
Blender importer failing to import files that used to work

### ISSUE THREAD

**Issue by jamesdolan** [assimp/assimp#2016]
When updating to latest master, Blender files that used to load no longer do with error output similar to the following...

```
assimp: Info,  T0: Load $$$___magic___$$$.
assimp: Info,  T0: Found a matching importer for this file format: Blender 3D Importer 
http://www.blender3d.org.
assimp: Info,  T0: Import root directory is './'
assimp: Info,  T0: BLEND: Blender version is 2.79 (64bit: true, little endian: true)
assimp: Info,  T0: BlenderDNA: Dumped dna to dna.txt
assimp: Warn,  T0: <add reason>
assimp: Skipping one or more lines with the same contents
assimp: Warn,  T0: BlendDNA: Did not find a field named `flags` in structure `Lamp`
assimp: Info,  T0: (Stats) Fields read: 701060, pointers resolved: 269, cache hits: 17166, cached objects: 113
**assimp: Error, T0: Validation failed: The mesh SomeMeshName contains no vertices**
```

...and if I open the file in blender and look at the offending mesh (e.g. 'SomeMeshName') does indeed have verts (44 tris, 84 verts). And if I roll back to an older assimp, the particular mesh in question does get loaded without issue and is visible.

Previously was using this version: https://github.com/assimp/assimp/tree/45892d7fe99c6c35d89f491af43f313e84e1e395

**Comment by jamesdolan** [comment]
Attached is a file that reproduces the issue.
[test.blend.zip](https://github.com/assimp/assimp/files/2100444/test.blend.zip)

**Comment by CwTCwT** [comment]
can/should i check this issue (reproduce and find the bug)?

**Comment by CwTCwT** [comment]
@jamesdolan i issued a pullrequest to solve this issue, caused by newly added CustomData support (base cause is somehow strange design: number of vertices (re)set when setting UVs, i commented the belonging part in the CustomData pullrequest). 
i could verify number of faces (44) but number of vertices were different in unittests result (132 <> 84), assuming you used some setting to minimize number of result vertices.
in unittest i only loaded the file with aiProcess_ValidateDataStructure.
i added your blender file to unittest, hope this is ok.
every additional blend file to support unittesting makes the lib better and more reliable.

**Comment by jamesdolan** [comment]
Thanks! For reference my loading flags are aiProcessPreset_TargetRealtime_MaxQuality | aiProcess_PreTransformVertices
