### ISSUE TITLE
Example how to create and export a scene

### ISSUE THREAD

**Issue by devurandom** [assimp/assimp#203]
I want to export a mesh I create myself using Assimp. However, I could not find an example on how to do that. I tried building the aiScene structs myself, using malloc and such, but that crashes Assimp, so I assume I need to initialise e.g. the private data somehow.

So my question is: How do I create a scene manually and then export it to a file, all using the C API.

**Comment by mxgrey** [comment]
I'd like to bump the issue raised by @Jadugar : I'm attempting to manually construct an aiScene, but I'm getting linking (undefined reference) errors for the constructor and destructor of aiScene. My project is definitely successfully linking to the assimp library. There are no other issues with using assimp. Importing scenes works perfectly fine. Only explicitly constructing and deleting aiScenes is causing any problems.

I've tried building my library as static as well as shared, but neither fixes the undefined reference issue.

I'm on Ubuntu 14.04 compiling with g++ 4.9.2 and using libassimp.so.3.0.1264.

**Comment by devurandom** [comment]
Maybe my lua-assimp code helps you do it? It worked nicely, back when I wrote it.

Obviously it contains lots of Lua C API code, as it converts Lua tables to an Assimp scene, but I think you should be able to understand how to do it from there. Start at _convert_scene and then follow the calls to the other _convert functions.

https://github.com/devurandom/lua-assimp/blob/master/assimp.c#L504

**Comment by mxgrey** [comment]
@devurandom Very clever! That trick would definitely help with constructing, although it wouldn't help with destructing. Since the aiScene owns so many raw pointers, it's important that all those resources get deleted during destruction. A memset to zero also wouldn't instantiate the "private data" field of the aiScene, although truthfully I have no idea how important or relevant that field is (it probably wouldn't be important at all for my uses).

**Comment by devurandom** [comment]
Your right, my implementation leaks a lot. Will fix that.

**Comment by ColinGilbert** [comment]
Its an interesting usecase that I also considered often enough, but wouldn't it be simpler to use a mesh library that exports to simple, common formats and import it into Assimp from an existing loader? Then a dev would be exposing him or herself to a bare minimum of third-party API. Are there any reasons other than speed of execution (which may well be very valuable) in which using the internal API may be preferable? I'd really like to know if there are any limitations that could be overcome by doing so.

**Comment by mxgrey** [comment]
@ColinGilbert , in my case I'm working on a dynamics and simulation package where *most* of the time we want to load the geometry of our robot models from arbitrary mesh file formats, so of course we use assimp the way it's meant to be used for that. But once meshes are loaded, we like to keep the data stored in assimp data structures, because it would make very little sense to invent our own data structures for storing the loaded meshes. Since we're using assimp to store our data, the assimp data structures essentially become the interface for all mesh-related activities, which is mostly rendering, but it may also include simulating soft objects (which involves moving around vertices to respond to external forces) or breaking objects apart (which involves creating and destroying faces).

One of the things we want to be able to do is programmatically generate meshes from scratch. This is where we've been running into issues with construction and destruction. We've implemented some workarounds to deal with constructors and destructors not being available for aiScene and aiMaterial, but it would probably be better if the assimp library simply offered constructors and destructors for those.

**Comment by mkoval** [comment]
@mxgrey Did you find a solution to this?

Unsurprisingly, since we're using the same software package, I ran into a similar issue. :smile:

**Comment by mxgrey** [comment]
I just wound up writing definitions for constructors and destructors inside my own library, and so those are the functions that are linked to when I manually construct and destruct assimp data structures.

**Comment by mkoval** [comment]
@mxgrey I believe I found the source of our problem. Recent Debian builds of Assimp are missing C++ symbols. See [this Debian bug report](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=775890).

**Comment by michaeltanner** [comment]
@tmoerwald, I had a similar issue and fixed it by adding the following line to the top of my imports:

`#include <assimp/IOSystem.hpp>`

**Comment by Aspirisha** [comment]
Hello! 
I have recently faced the similar problem and decided to apply the solutions proposed here. Basically what I need is to merge two 3d models into one, applying simple transforms to them. 

I ended importing both of them via assimp, copying the scenes so that i can modify them (with `aiCopyScene`),  and then the fun begins. Although I extend meshes of the destination model with meshes of the scene I am merging in (with all the vertices, indices, faces copied properly), exporter seems to ignore this and just writes the original scene. 

I am pretty sure I miss something, I just don't understand what. 

```C++
void ModelMerger::merge_with(const ModelMerger &other,
                                const glm::mat4x4 transform) {
    aiMesh ** new_meshes = new aiMesh*[scene->mNumMeshes + other.scene->mNumMeshes];
    memcpy(new_meshes, scene->mMeshes, scene->mNumMeshes * sizeof(aiMesh*));
    delete[] scene->mMeshes;
    scene->mMeshes = new_meshes;
    for (int i = 0, offset = scene->mNumMeshes; i < other.scene->mNumMeshes; i++, offset++) {
        aiMesh *mesh = other.scene->mMeshes[i];
        aiMesh *copy_mesh = scene->mMeshes[offset] = new aiMesh;

        copy_mesh->mNumVertices = mesh->mNumVertices;
        copy_mesh->mVertices = new aiVector3D[mesh->mNumVertices];
        copy_mesh->mPrimitiveTypes = mesh->mPrimitiveTypes;
        for (int j = 0; j < mesh->mNumVertices; j++) {
            glm::vec4 v(mesh->mVertices[j].x, mesh->mVertices[j].y, mesh->mVertices[j].z, 1);
            v = transform * v;
            copy_mesh->mVertices[j] = aiVector3D(v.x, v.y, v.z);
        }
        // copy_mesh->mMaterialIndex = mesh->mMaterialIndex; // FIXME
        copy_mesh->mName = mesh->mName;
        copy_mesh->mNumFaces = mesh->mNumFaces;
        if (mesh->mNormals) {
            copy_mesh->mNormals = new aiVector3D[mesh->mNumVertices];
            for (int j = 0; j < mesh->mNumVertices; j++) {
                glm::vec4 v(mesh->mNormals[j].x, mesh->mNormals[j].y, mesh->mNormals[j].z, 0);
                v = transform * v;
                copy_mesh->mNormals[j] = aiVector3D(v.x, v.y, v.z);
            }
        }
        copy_mesh->mFaces = new aiFace[mesh->mNumFaces];
        for (int j = 0; j < mesh->mNumFaces; j++) {
            copy_mesh->mFaces[j].mNumIndices = mesh->mFaces[j].mNumIndices;
            copy_mesh->mFaces[j].mIndices = new unsigned[mesh->mFaces[j].mNumIndices];
            memcpy(copy_mesh->mFaces[j].mIndices, mesh->mFaces[j].mIndices,
                   mesh->mFaces[j].mNumIndices * sizeof(unsigned));
        }
    }
    scene->mNumMeshes += other.scene->mNumMeshes;```

**Comment by clouds56** [comment]
@Aspirisha you copied meshes into new scene but not add them to the node tree.
See `scene->mRootNode`.

**Comment by alessandroAM** [comment]
Hello, 
I'm trying to export my aiScene (which worked correctly with a previous assimp source), I get a crash every time that the procedure ends and the export function it's called. I subclassed aiScene and the constructor looks like this:

`customAiScene::customAiScene()
{
    mFlags = 0;
    mRootNode = NULL;
    mNumMeshes = 0;
    mMeshes = NULL;
    mNumMaterials = 0;
    mMaterials = NULL;
    mNumAnimations = 0;
    mAnimations = NULL;
    mNumTextures = 0;
    mTextures = NULL;
    mNumLights = 0;
    mLights = NULL;
    mNumCameras = 0;
    mCameras = NULL;
    mPrivate = NULL;
    exporter = new Assimp::Exporter();
    int n = exporter->GetExportFormatCount();
    for (int i = 0; i < n; i++) {
        const aiExportFormatDesc* formatDescription = exporter->GetExportFormatDescription(i);
        wxString sDesc = wxString::FromUTF8(formatDescription->description);
        wxString sExt = wxString::FromUTF8(formatDescription->fileExtension);
        wxString sID = wxString::FromUTF8(formatDescription->id);
        MyApp::showMessage(wxString::Format(wxT("export format: %s,%s,%s"), sDesc, sExt, sID), "l");
    }
}`

Later on, after setting the data, I export the scene:
`exporter->Export(this, exportFormatDesc, filePath);`

As I said, with a previous assimp version (BTW, there is a way to query which one I'm using?) it is working correctly. Thanks for any help.

**Comment by JC3** [comment]
Here, guys. I just struggled a bit, too. Here is the shortest example (that is still clear) I could make for how to create a scene with a mesh:

        // create vertices and faces, then pack into an aiMesh

        aiVector3D *vertices = new aiVector3D [] {          // deleted: mesh.h:758
            { -1, -1, 0 },
            { 0, 1, 0 },
            { 1, -1, 0 }
        };

        aiFace *faces = new aiFace[1];                      // deleted: mesh.h:784
        faces[0].mNumIndices = 3;
        faces[0].mIndices = new unsigned [] { 0, 1, 2 };    // deleted: mesh.h:149

        aiMesh *mesh = new aiMesh();                        // deleted: Version.cpp:150
        mesh->mNumVertices = 3;
        mesh->mVertices = vertices;
        mesh->mNumFaces = 1;
        mesh->mFaces = faces;

        // a valid material is needed, even if its empty

        aiMaterial *material = new aiMaterial();            // deleted: Version.cpp:155

        // a root node with the mesh list is needed; if you have multiple meshes, this must match.

        aiNode *root = new aiNode();                        // deleted: Version.cpp:143
        root->mNumMeshes = 1;
        root->mMeshes = new unsigned [] { 0 };              // deleted: scene.cpp:77

        // pack mesh(es), material, and root node into a new minimal aiScene

        aiScene *out = new aiScene();                       // deleted: by us after use
        out->mNumMeshes = 1;
        out->mMeshes = new aiMesh * [] { mesh };            // deleted: Version.cpp:151
        out->mNumMaterials = 1;
        out->mMaterials = new aiMaterial * [] { material }; // deleted: Version.cpp:158
        out->mRootNode = root;

        // and we're good to go. do whatever:

        Assimp::Exporter exporter;
        if (exporter.Export(out, "objnomtl", "triangle.obj") != AI_SUCCESS)
            cerr << exporter.GetErrorString() << endl;

        // deleting the scene will also take care of the vertices, faces, meshes, materials, nodes, etc.

        delete out;

Verified no leaks by manual code review. Things to note:

- All data must be allocated on the heap to cooperate with destructors.
- The scene must have, at minimum: a mesh, a *valid* (but can be empty) material, and a root node. The root node must list the meshes you want to export (it's not enough to just have them in the aiScene list), but doesn't need anything else.
- You don't need to worry about private data or initializing unused members (the constructors do all of this).
- I didn't include normals in the example but you can if you want.
- Deleting the aiScene will in turn clean up everything else you've allocated (I've indicated deletion points in comments, references assimp 5.0.1).

**Comment by JC3** [comment]
> I'm trying to export my aiScene (which worked correctly with a previous assimp source), I get a crash every time that the procedure ends and the export function it's called. I subclassed aiScene and the constructor looks like this:

You had two issues:

- Don't modify `mPrivate`.
- You need one valid material. 

Also, don't subclass `aiScene` (or anything else in this library): The base destructor is *not* virtual and you run a high risk of trouble. Also you never really need to. All that aside, though, if you do it anyways, you don't need to zero-initialize the members, the base constructor already does all that. :)

**Comment by forestgril2** [comment]
Thanks JC3! I looked here a month ago and there was no answer of Yours! Now I am back, I need it and You are just on time with Your help ;)

**Comment by JC3** [comment]
> Thanks JC3! I looked here a month ago and there was no answer of Yours! Now I am back, I need it and You are just on time with Your help ;)

No worries; one minor thing -- be aware of #3781 if you plan on using the PBRT exporter (which I think is very new and doesn't actually work properly because of #3783 anyways). For that exporter, you'll have to also do `scene->mMetaData = new aiMetadata();` as a workaround. It only applies to that one exporter, otherwise it doesn't matter.

**Comment by JC3** [comment]
> Thanks JC3! I looked here a month ago and there was no answer of Yours! Now I am back, I need it and You are just on time with Your help ;)

No worries; couple of minor things I discovered in the latest version of the library (not present in the 5.0.1 bugfix release on the releases page, but present in the current master):

- #3778 requires a workaround for the 3DS, GLTF, and PBRT exporters. You need to add `mesh->mPrimitiveTypes = aiPrimitiveType_TRIANGLE;` (or whatever primitives your mesh has, see docs for `mPrimitiveTypes`) to your mesh or those exporters will crash.
- #3781 requires a workaround for the PBRT exporter. For that exporter, you'll have to also do `scene->mMetaData = new aiMetadata();` as a workaround. It only applies to that one exporter, otherwise it doesn't matter. I think this exporter is super new, though, and also it doesn't really work anyways because of #3783, so you may not care about this.

I don't know when those were introduced, I just know it was some time between the `v5.0.1` tag (8f0c6b0) and the master branch as of a few days ago (cd42b995). They're simple enough, though. 

I'll edit my previous post now to include those.

**Comment by JC3** [comment]
Two additional issues have come that also require workarounds (they're in the current master but I do *not* know if they're in the official 5.0.1 release):

- #3814 requires a workaround for the X3D exporter. You need to set `mesh->mName` to something, and all your meshes should have unique names, otherwise it'll write mildly malformed files which *may* cause issues down the line if you're unlucky. One quick-and-dirty name generation strategy (among others) is:

        char name[100];
        snprintf(name, sizeof(name), "mesh_%p", (void *)mesh);
        mesh->mName.Set(name);

- #3816 requires a workaround for the 3MF exporter. *Only* meshes in the *immediate child nodes* of the root node are exported. Meshes in the root node or in grandchildren and beyond are ignored. So for this you have to make sure you use a child of the root instead. In the case of my example above, you can take the drop-in approach of modifying the scene after it's created and inserting a new root above the old one, e.g.:

        aiNode *oldroot = scene_->mRootNode;
        scene_->mRootNode = new aiNode();
        scene_->mRootNode->addChildren(1, &oldroot);

  Or you could just build the scene with that structure right off the bat. Whatever floats your boat.

  You could also take a more generic approach at the point where you export, although to be safe you'd probably want to copy the scene and operate on the copy (pseudo-ish code, `Export` is just a placeholder for whatever):

        aiScene *scene = ...;
        string format = ...;

        if (format == "3mf") {
            aiScene *exportScene;
            aiCopyScene(scene, &exportScene);
            aiNode *oldroot = exportScene->mRootNode;
            exportScene->mRootNode = new aiNode();
            exportScene->mRootNode->addChildren(1, &oldroot);
            Export(exportScene, format);
            delete exportScene;
        } else {
            Export(scene, format);
        }

   That code wouldn't work as-is for general use (e.g. you don't want to modify the scene if it's already in a form that makes the 3MF exporter happy, and *none* of these workarounds apply to scenes with more complex trees, which is less trivial), but, it's helpful for basic single-node scenes at least.

I have not yet edited my example code above to include these workarounds, so you'll have to add them yourself. Also, if you're building more complex scenes and you want to export 3MF, you'll need to come up with your own workaround. Conversely, if you don't care about 3MF output at all, you don't need to do any of that.

Like I said, though, I don't know if these issues are present in the 5.0.1 release on the releases page -- so if they *aren't*, then you don't need the workarounds.

**Comment by forestgril2** [comment]
> 
> Two additional issues have come (...)

Thanks Jason, I will try this out. Actually I have issues with STL export (rel 5.0.1) - have You tried that? Strangely - in my app in Debug mode it will copy the master scene (is exported twice - wrongly of course) and in Release mode it will not export other attached scenes (beyond the master scene.) Could You please try it with Your implementation? Otherwise I will need to write STL exporter myself, rather than fix Assimp, the format is quite simple.

**Comment by forestgril2** [comment]
Well, identical issues are with "objnomtl" export as well..,

**Comment by JC3** [comment]
> Actually I have issues with STL export (rel 5.0.1) - have You tried that?

The only issue that I am *aware* of right now with STL in v5.0.1 is #3756: Exported ASCII STL files are slightly broken (so you'd either want to fix the issue by hand in your assimp source -- [very easy fix](https://github.com/assimp/assimp/commit/8ba1d38deac09228aa58589f2a09e64a80584f16?branch=8ba1d38deac09228aa58589f2a09e64a80584f16&diff=unified) or use binary STL instead). This doesn't sound related to your problem though (although it is a potentially serious issue; I highly recommend patching your assimp and rebuilding it, regardless).

> Well, identical issues are with "objnomtl" export as well..,

I'm not aware of any particular issues with the obj[nomtl] exporters, but I also haven't focused on them much (I've been doing a lot of assimp testing but haven't gotten to obj yet; I haven't noticed anything yet though).

>  in my app in Debug mode it will copy the master scene (is exported twice - wrongly of course) and in Release mode it will not export other attached scenes (beyond the master scene.)

Hmm.... I am having trouble understanding what you mean here. :) What is the "master scene" and "other attached scenes"? Do you perhaps mean "meshes"?

**Comment by forestgril2** [comment]
Well, I am trying to use Assimp::SceneCombiner::MergeScenes, to generate one scenes out of many models. Specifically - I am creating support geometries for an STL model, and want to export it together with the STL model (but I modify the header to let the app know, how many faces are for model, how many for the supports, for the stand etc.).

Assimp::SceneCombiner::MergeScenes uses SceneAttachmentInfo structures to pass scenese to merge. 
You can have a look, if You wish: https://github.com/forestgril2/Ubot3D/blob/master/src/cpp/FileImportExport.cpp

BTW, this is very WIP ;)

**Comment by JC3** [comment]
Ah OK, that is much clearer. Give me some time to look more closely and run a few tests to see what assimp's deal is here.

> You can have a look, if You wish: https://github.com/forestgril2/Ubot3D/blob/master/src/cpp/FileImportExport.cpp,

Awesome, thanks. I'm going to take a look at what's going on here. If you don't mind, I will create an issue in that repo to continue this discussion after I look at this. I don't want to get *too* off topic in this thread. :D

I will keep you posted.
