### ISSUE TITLE
GLTF KHR_texture_transform

### ISSUE THREAD

**Issue by Danny-Kint** [assimp/assimp#2119]
Any plans to support this [feature](https://github.com/KhronosGroup/glTF/tree/master/extensions/2.0/Khronos/KHR_texture_transform)?

**Comment by ardenpm** [comment]
I just came across this also testing our app against the 2.0 sample model repository in the TextureTransformTest. Would be good to at least store the properties. I guess they would need to be stored as material properties related to textures similar to the wrapping modes?

Had a quick look at what might be involved in implementing it and since most of the extension detection stuff is there it looks like first the properties would need to be added to the glTF2Asset and then converted into material properties by flattening the offset, rotation and scale into something storable in the existing AI_MATKEY_UVTRANSFORM_BASE key.

I wouldn't like to get too far into it before hearing from someone if this might be the right approach.

**Comment by Starnick** [comment]
Sounds like a good feature to support IMO

**Comment by sayduck-daniel** [comment]
@kimkulling I am indeed interested in this feature.

**Comment by Silvaire** [comment]
I also believe this extension is a very good one, with most glTF applications supporting it already.

**Comment by silvainSayduck** [comment]
I also believe this extension is a very good one, with most glTF applications supporting it already.

**Comment by corporateshark** [comment]
@kimkulling I'm interested as well. 

It seems `AI_MATKEY_UVTRANSFORM_BASE` is unused in the glTF2 loader. Is it possible to put the combined UV matrix in there?

**Comment by kkulling** [comment]
I am currently working on this feature

**Comment by ardenpm** [comment]
Excellent! Just a heads up, I imagine it will be tricky to test this feature until issue #2718 is also addressed since the underlying UVs won't be correct. I'm not sure if people are reproducing that issue as no one else commented on it yet.

**Comment by ardenpm** [comment]
Unfortuantely there was a small issue with this. The y translation was taking its value from the X translation. I will submit a pull request with a change to fix that.

**Comment by ardenpm** [comment]
Have been doing further testing and unfortunately the rotation values are not coming through. I haven't been able to determine why yet and will need to continue investigating. The code looks right, I tried some different ways to do the same thing but they don't make any difference.

**Comment by ardenpm** [comment]
I haven't identified the rotation issue yet, however just to note for glTF the UV rotation is around the origin, which in glTF is the top left of the texture, where as Assimp documents the mRotation member of aiUVTransform as being around 0.5,0.5 (center of the image). As a result it may not be possible to represent as a strict TRS when combined. Further investigation needed.

**Comment by ardenpm** [comment]
Ok, so the commit referenced above addresses the issue with rotations not being retrieved when using aiGetMaterialUVTransform (and just Get() on the material itself since that calls that). Previously it was only possible to obtain the rotation by manually calling aiGetMaterialFloatArray.

The issue mentioned where rotation origins differ above still remains and I think is the last item that would need to be addressed.

**Comment by ardenpm** [comment]
So the issue is actually a little more complex. Basically the coordinate system for each of the transformation values is different between glTF and Assimp. Here are the origins (at least I assume Assimp uses 0,0 at the bottom left of textures) in the Assimp space.

| Component   | glTF Origin | Assimp Origin |
| ------------| ----------- | ------------- |
| Translation | 0,1         | 0,0           |
| Scale       | 0,1         | 0,0           |
| Rotation    | 0,1         | 0.5,0.5       |

I suspect the easiest way to handle this will be to deal with them as matrices then decompose them back to the translation rotation scale components afterwards. This is going to be a bit more involved than hoped.

**Comment by ardenpm** [comment]
Have now implemented the change of coordinates needed and will do a PR. Results now match the glTF 2.0 test case [here](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/TextureTransformTest). Quick rendering from our software.

![KHR_texture_transform](https://user-images.githubusercontent.com/5742686/69682583-f6b83f00-1105-11ea-905b-58160ac24172.jpg)

Hopefully this now makes a complete implementation for this extension.

**Comment by Danny-Kint** [comment]
I'm afraid there is still an issue with the implementation of this extension.
With just this simple test
```cpp
    Assimp::Importer importer;
    auto scene = importer.ReadFile("TextureTransformTest.glb", aiProcess_TransformUVCoords);
    Assimp::Exporter exporter;
    auto res = exporter.Export(scene, "glb2", "TextureTransformTest.glb", 0);
```
This is the output I get:
![image](https://user-images.githubusercontent.com/35391922/103138050-db37b300-46ce-11eb-8682-e41d2f40021b.png)

Plus it would also be a good thing to export the uv transform as an extension without modifying the UVs by applying the postprocessing `aiProcess_TransformUVCoords`.
