### ISSUE TITLE
(Regression) FBX UV mapping issues

### ISSUE THREAD

**Issue by rickomax** [assimp/assimp#2145]
Hi.

The following commit breaks UV data loading on some Paint 3D FBX files:
[https://github.com/assimp/assimp/commit/de8adacb54570ca58aa233ed59e5210cefb6f497](https://github.com/assimp/assimp/commit/de8adacb54570ca58aa233ed59e5210cefb6f497)

@aavenel validating a Direct data trying to use indices is totally wrong.

Best regards,
Ricardo Reis.

**Comment by aavenel** [comment]
Hi Rickomax,

Could you test if this pull request fix your issue ? https://github.com/assimp/assimp/pull/2134

**Comment by aavenel** [comment]
Reverting de8adac will just reintroduce another issue and some fbx won't load at all. The right fix is the one by Loïc on #2134. See the whole discussion here https://github.com/assimp/assimp/pull/2037

**Comment by rickomax** [comment]
@aavenel direct data shouldn't have indices. Why are you trying to validate such data in your commit?

**Comment by aavenel** [comment]
Again, the right fix is on #2134.
` if (!HasElement(source, dataElementName)) {`

We access `dataElementName` a few line below so this is the one we need to check.

Commit de8adac is wrong because it only restore bad code to fix a bigger regression that prevented loading some fbx (see for example box.fbx on the unit tests). We need to fix the typo on this commit by using PR #2134.

The initial goal for checking this is a bug on Paint3D :
https://github.com/assimp/assimp/pull/1735

I think a PR to have unit test for fbx UV map would be welcome if you want!

**Comment by aavenel** [comment]
Hi Rickomax,

#2134 has been merged on master. Do you still have the same problem ?

**Comment by rickomax** [comment]
@aavenel your commits fixed the issue. Thank you!
