### ISSUE TITLE
FBXConverter::GetUniqueName makes loading slow for some models

### ISSUE THREAD

**Issue by mlavik1** [assimp/assimp#2390]
`FBXConverter::GetUniqueName` makes loading very slow on models with many duplicate names (`Assimp::FBX:Model::name`).

I have had this issue on several models: Unfortunately I cannot share these models, since they belong to our customers.
In the worst casees, the function ended up doing several thousand iterations, causing import time to take over an hour.

I'm not that familiar with the FBX format, so please tell me if I wrong, but I think a better solution would be to use a map of names(string) and name instance count (unsigned int).

**Comment by aavenel** [comment]
Hi mlavik1,

Are you using a recent assimp version ?
There was this pull request a few month ago which might have adressed this issue https://github.com/assimp/assimp/pull/2076

**Comment by mlavik1** [comment]
Hi @aavenel ,
Yes, I'm on master branch.
After that change, we are still doing N iterations with N string modifications (where N = number of objects with the same name).

**Comment by mlavik1** [comment]
I will create a PR with my suggested change, so you can see what I mean. (feel free to reject it)

**Comment by mlavik1** [comment]
By the way, the models where this was an issue were exported from Navisworks. Having this many duplicate names might be an edge-case, but for us it was a big issue that had to be fixed.
After doing my change (see PR) loading time was reduced from almost two hours to less than two minutes.

**Comment by aavenel** [comment]
Just looked at the code, and I think you are right! 
(I'm not the maintainer of assimp, so it's not my call to accept/reject PR ;) )

**Comment by muxanick** [comment]
I have a change in that function as well, replaced std::set for std::unordered_set and then changed prefixes for names (take parent name if child name is empty), mostly bad performance comes from empty names and because assimp doesn't support pivot transform (makes additional node for it and requests node name).
That makes speed up to 100 times.
Before FBX file was importing for a few hours, but after that a few seconds.
I am still trying to get these changes to github, that's complicated.

For the pull request above, does it work if node with added numbers already exists in the graph?
like:
Root -> Node -> Node -> Node001 (this name is in FBX)
it will look into `Node`, adds to map Node with 0 index
then 'Node` again: Node in the map, increase index and make Node001 node,
then `Node001`: It is not in the map, it will add it with index 0.
So, we will have two names with `Node001` name, is it?

**Comment by mlavik1** [comment]
Hi @muxanick,
Nice catch! That is indeed an issue.
I guess I could add back the set lookup to make sure we don't get duplicates. But I don't want to make the code too messy, so I'll give it some thought after the weekend.

Your change sounds great (so please submit a PR when you can), but on some of the models where I had this issue there were a lot of nodes with non-empty duplicate names as well.

I'll close my PR and make a new one when I'm done.

**Comment by kimkulling** [comment]
This is already on master as far as I know. I will close this one.
