### ISSUE TITLE
assimp.exe was not found. static linking runtime error

### ISSUE THREAD

**Issue by khanIdris** [assimp/assimp#2444]
I'm using static linking to link my program with assimp. assimp and my program, both build successfully, however when I run my program, it prompts with the following error
"the code execution cannot proceed because **assimp.exe** was not found. Reinstalling may fix this problem."

**Comment by kkulling** [comment]
Wher do you run it? In the console or in a debugger?

**Comment by khanIdris** [comment]
in the debugger.

**Comment by khanIdris** [comment]
MSVC 2017

**Comment by kimkulling** [comment]
Have you enabled the correct project? Normally you have to select assimp_cmd or the viewer instead of the dll-project. The dll-project does not have any executable to run. So please make sure that you are trying to run the correct project.

Please check also that the working directory of your debugging run is configured properly. YOu can do this in the property page for your project, select the Debugging-tab in the solution ( right mouse -> properties -> debugging.

**Comment by nathans3** [comment]
Hello I am facing a similar problem - I am linking my project to LightGBM  package which is stored in a different location than my project is located. All built and run well in Release mode. In debug mode however after a successful build, when I run I get the message that "the code execution cannot proceed because lightgbm.exe was not found. Reinstalling the program may fix the problem". However, lightgbm.exe does exist in the x64/Debug folder of LightGBM, and this path is successfully read by VS because it gets the lightgbm.lib file from the same path. I am using VS 2019. Please help, thank you! Nathan
