### ISSUE TITLE
Assimp shall import of pointcoulds

### ISSUE THREAD

**Issue by kimkulling** [assimp/assimp#254]
Yes, it would be nice if Assimp could read point clouds. I think this would become a nice feature since point clouds are used more and more with 3d printers etc...
Do you think this is easy to implement in a near future version? Or maybe provide me with a patch at the moment?

Thanks for your assistance!

**Comment by MarekAtGoogle** [comment]
Hi, I am just curious if point clouds are already supported? I was trying to load a ply but I was not able to get the points out in any way.

Thanks!

(As a side effect, option aiProcess_Triangulate will take up to minutes to finish with large point clouds.)

**Comment by chrisidefix** [comment]
I would certainly be interested in getting this to work as well, if it isn't behaving as expected at the moment. PLY has multiple and flexible definitions, though - but I guess we can agree that no face elements shouldn't assume triangle (that's stl). @kimkulling I am going to give this a shot unless you already have something?

**Comment by kimkulling** [comment]
I do not have any implementation at the moment. So if someone wants to go for it: have fun :-).

**Comment by swomack** [comment]
Hi @chrisidefix !

Is there any update regarding this?

**Comment by kimkulling** [comment]
There were some other requests, yes!

**Comment by chrisidefix** [comment]
Hello @swomack - I haven't been working on this and am not planning on
importing / exporting point clouds with assimp - seems like this wouldn't
be difficult to implement, but probably time consuming.

**Comment by Frooxius** [comment]
Hello,

I would  also like to join this issue. Assimp 4.0.1 still seems to import point clouds incorrectly, in several different formats.

I have exported a point cloud from Agisoft PhotoScan in several formats that Assimp supports, but each one of them fails in a different way:

OBJ - Produces generic "Failed to read file"
PLY - Generates nonsensical triangles, rather than point primitives (I believe that's the same issue as originally reported)
DXF - Produces "This file contains no 3D data" message

I have tested each with Blender and it imports them correctly.

If it helps, here are the test files: https://cp.sync.com/dl/390004720#bnybycbr-nrz6nkf7-66m78zgz-b9bc9xpn

It includes some extra formats that the software can export, adding support for those might also be potentially interesting in the future, but tangential to this issue.

**Comment by kimkulling** [comment]
OK, good to know! Have you also tried to disable model validation?

**Comment by JekaS178RUS** [comment]
Any update on this? I am will be very happy to be able read and write point clouds with assimp in OBJ and PLY

**Comment by JekaS178RUS** [comment]
Hello again!
As I can see when importing PLY format with only points data there is one mesh in scene from which I can extract points for my cloud. But when importing OBJ file with same data, there is no any data in scene at all. It will be great if you could implement same behaviour for obj files as in ply importer.

**Comment by kimkulling** [comment]
Done, see onj-importer!
