### ISSUE TITLE
Setup of the solution via CMake either 64bit or 32bit

### ISSUE THREAD

**Issue by RumbleballTheReal** [assimp/assimp#2595]
Building the solution with CMake only allows for one target type. How do you get a solution that can build both targets?

**Comment by RichardTea** [comment]
This is the way CMake works.
It's deliberate to minimise unnecessary recompilation and linker errors as it supports a huge array of target toolchains and architectures.

An invocation of CMake generates a throwaway 'makefile', 'solution' or equivalent for a _single_ target compiler and architecture/platform combination. You feed it to the toolchain (eg MSBuild, make) then destroy it.

x86, amd64 (x64), arm, arm64 etc are all different architectures/platforms (and usually different compilers too), so must be done in separate cmake invocations.

Usually you'll create build folders for each target architecture (eg "assimp-build-x64" and "assimp-build-x86") and then invoke cmake for each target architecture.

This ensures that you do not end up with broken builds that have some object files compiled for x86 and others for amd64, which won't link or crash at start.

**Comment by RumbleballTheReal** [comment]
That means you have a solution to edit the source files but on compilation you create additional temporary solutions that create the target files and kill everything after the builds? 
Do you create a subfolder for each target solution in Assimp root folder? I did that the first time I created the solution with CMake, but the binaries were put in different directories compared to placing the solution in Assimp root folder. 
Very confused about this.

**Comment by RichardTea** [comment]
Yes, it's a bit confusing for MSBuild (Visual Studio C++) targets because (since 2012?) the *.sln and *.vcxproj are also what's fed the compiler toolchain (MSBuild). IIRC Mac is the same with xcode.

Recent versions of Visual Studio now support CMake projects directly, though I'm not sure how well.

By default CMake does "shadow builds", where all the intermediate (obj) and final (dll, exe, pdb) build artefacts go in the build folder.

However there are also an "Install" and "Update Libs and PDB" subprojects that will copy the final artefacts to defined LIB and BIN directories. I don't recall how you set those under Windows as I'm deploying another way.

**Comment by RumbleballTheReal** [comment]
Is this "throw away project workflow" general behavior for CMake or is this specific to Assimp?
Why not use the created CMake solution for development?

**Comment by RichardTea** [comment]
It sounds like you've only ever worked with Windows/MSVC projects. This must be truly mindblowing!

This is the general behavior of all cross-platform project definition systems.

It must be so, because every combination of operating system, compiler and architecture needs different paths, source, defines (`#ifdef _WIN32`), compiler and linker options, provided in various different ways.

CMake, Qt's qmake, Mozilla's "mach" et al do this by reading "cross-platform" project files and then generating "platform-specific" build system for your chosen OS/compiler/architecture.

Eg CMake reads a tree of "CMakeLists.txt" cross-platform project files.
On Linux it outputs a set of "makefiles", on Windows a *.sln and some *.vcxproj, and on macOS an xcodeproj.

A .sln and set of .vcxproj are _only_ usable by appropriate versions of the Microsoft Compilers.
They can't be used by mingw, GCC, Clang, xcode.

The generated *.sln, *.vcxproj (and some header and source files) are specific to your particular platform, chosen options and sometimes your computer - eg the paths to _your copy_ of dependent libraries, like Qt5.

Further reading:
https://cmake.org/
https://preshing.com/20170511/how-to-build-a-cmake-based-project/

_(In reality, Visual Studio and MSBuild actually create throwaway "solutions" each time you compile, for similar reasons. They just hide them away so you don't see them.)_

**Comment by kimkulling** [comment]
So the best way to adress this is just:
```
cmake CMakeLists.txt -G "<Your VS>"
cmake --build .
cmake CMakeLists.txt -G "<Your VS> Win64"
cmake --build .
```
Works for me.

**Comment by RumbleballTheReal** [comment]
Thank you guys for giving more information on this.

Kim Kulling <notifications@github.com> schrieb am Di., 27. Aug. 2019, 16:26:

**Comment by RumbleballTheReal** [comment]
Ok, further trying to understand how CMake works and how to use it with Assimp.

Download github/master to MyDir/Assimp
Run `cmake CMakeLists.txt -G "Visual Studio 15 2017` on MyDir/Assimp
_That will create the Build System (Visual Studio 15 2017) in MyDir/Assimp for Win32_
Run `cmake -- build .`
_To execute the Build System and build the target (which defaults to Debug)_

Now I have the problem that MyDir/Assimp is source as well as build directory, which is also discuraged by CMake (and yah, thats always bad). But as building CMake does also generate the config.h file that is placed in MyDir/Assimp/include it is not possible to define a subdirectory for the Build System that is build by CMake.

Running `cmake CMakeLists.txt -G "Visual Studio 15 2017 Win64` on MyDir/Assimp 
_Fails cause another build system is already defined in that directory_

So I need to kill the created Build System but how do I do that? I can't just remove the MyDir/Assimp as that is also the source directory. The file cmake_uninstall.cmake seem to be what needs to get called to clear the the created Build System but how? calling `cmake -P cmake_uninstall.cmake` does not work as it is missing the cmake_manifest.txt file.

Am I supposed to have a copy of github/master for each build target (Win32/Win64/Linux/MacOs...)

**Comment by RumbleballTheReal** [comment]
Would like an anwser to my post before if possible @RichardTea @kimkulling 
Thanks

**Comment by pierremoreau** [comment]
> But as building CMake does also generate the config.h file that is placed in MyDir/Assimp/include it is not possible to define a subdirectory for the Build System that is build by CMake.

You actually can, cause the code handles it: the file is written as `${CMAKE_BINARY_DIR}/include/assimp/config.h`, and `${CMAKE_BINARY_DIR}/include` is added to the list of include directories, so the compiler will find it.

So, you could do something like:

1. Download to MyDir/assimp
2. Create a MyDir/win32 folder
3. From MyDir (for example), run `cmake -G "Visual Studio 15 2017" -S assimp -B win32` (`-S` to specify the source folder, and `-B` for the build folder)
4. Still from MyDir, run `cmake --build win32`
5. Create a MyDir/win64 folder
6. From MyDir (for example), run `cmake -G "Visual Studio 15 2017 Win64" -S assimp -B win64`
7. Still from MyDir, run `cmake --build win64`

**Comment by RumbleballTheReal** [comment]
Thank you @pierremoreau. I was more talking about delivery of the files to the target project (copy of includes and binaries). But as it turns out, you should write a script to copy files as needed.

https://github.com/assimp/assimp/pull/2646#issuecomment-531417449
