### ISSUE TITLE
C_Str() not working

### ISSUE THREAD

**Issue by jsemeda** [assimp/assimp#2747]
This was working in ver 4.8, as soon as I updated to ver 5.0 it started giving garbage
aiString texDiffusefile;
std::String dstMat->texDiffusePath;

srcMat->Get(AI_MATKEY_TEXTURE(aiTextureType_DIFFUSE, 0), texDiffusefile);
dstMat->texDiffusePath = texDiffusefile.C_Str();

the destination string has garbage in it while the source has a file name.

**Comment by neumont-gamedev** [comment]
I'm having some issues also. It seems like my texture names are being cutoff at the front. For example, "glass_dif.png" is showing up "s_dif.png" Not sure if it is 100% related to the above issue but could be.

		aiString string;
		if (ai_material->GetTexture(type, i, &string) == AI_SUCCESS)

string shows incorrect texture name.

**Comment by kimkulling** [comment]
PLease provide an example file and reopen the issue. 

Thanks a lot!

**Comment by marinjurjevic** [comment]
I am experiencing exactly the same issue as @neumont-gamedev described. First 4 characters are lost in texture path.

I think the problem is somewhere in [aiGetMaterialString](https://github.com/assimp/assimp/blob/master/code/Material/MaterialSystem.cpp#L289) function.

Down is attached screenshot with source and texture path output. Example is fresh clone from [LearnOpenGL](https://github.com/JoeyDeVries/LearnOpenGL) repo.

![2020-02-11-204513_1920x1080_scrot](https://user-images.githubusercontent.com/17838694/74273235-60f97c80-4d10-11ea-8820-c00189a04c33.png)

**Comment by turol** [comment]
`nanosuit.obj` loads correctly for me with `assimp info` and the texture names look correct. This might be related to #1993.
