### ISSUE TITLE
assimpTargets.cmake computes bad .dylib filename on macOS

### ISSUE THREAD

**Issue by gerkey** [assimp/assimp#2760]
I have assimp 5.0.0 installed on macOS Mojave via homebrew. There seems to be something wrong with the installed CMake configuration files, leading to generation of an almost-but-not-quite-right path for the assimp shared lib.

The installed CMake rules want to find `/usr/local/lib/libassimp.dylib.5`, while the installed filename is `/usr/local/lib/libassimp.5.dylib`.

Workaround: `cd /usr/local/lib; ln -s libassimp.5.dylib libassimp.dylib.5`.

Repro:

1. Put this content in a file called `CMakeLists.txt`:
```cmake_minimum_required(VERSION 3.5)
project(foo)
find_package(assimp)
```
2. Run `cmake .`
3. Get this error:
```CMake Error at /usr/local/lib/cmake/assimp-5.0/assimpTargets.cmake:85 (message):
  The imported target "assimp::assimp" references the file

     "/usr/local/lib/libassimp.dylib.5"

  but this file does not exist.  Possible reasons include:

  * The file was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and contained

     "/usr/local/lib/cmake/assimp-5.0/assimpTargets.cmake"

  but not all the files it references.

Call Stack (most recent call first):
  /usr/local/lib/cmake/assimp-5.0/assimp-config.cmake:1 (include)
  CMakeLists.txt:4 (find_package)
```

**Comment by kimkulling** [comment]
OK, thanks for the report. We need a MAC-maintenancer! I cannot test these kind of bugs!

**Comment by gerkey** [comment]
Unfortunately I can't sign up to be a maintainer, but I can propose a fix in this case: #2765.

I'm guessing that this problem on macOS has been present since the introduction of the `assimpTargets-release.cmake.in` file:

https://github.com/assimp/assimp/commit/b43cf9233703305cfd8dfe7844fce959879b4f0c#diff-60d8ac55f55af0788ee2bd53a5f840acR43

**Comment by meyerj** [comment]
The build of derived packages (e.g. ROS [geometric_shapes](https://github.com/ros-planning/geometric_shapes)) in macOS Mojave still fails for me because `ASSIMP_LIBRARIES` is set to just the filename in [assimpTargets-release.cmake.in:97](https://github.com/assimp/assimp/blob/84deb1db449b03d85c01d96eaa00e0f51fb86743/assimpTargets-release.cmake.in#L97):
```
[100%] Linking CXX shared library /Users/intermodalics/catkin_ws/devel_isolated/geometric_shapes/lib/libgeometric_shapes.dylib
/usr/local/Cellar/cmake/3.15.5/bin/cmake -E cmake_link_script CMakeFiles/geometric_shapes.dir/link.txt --verbose=1
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -O2 -g -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -mmacosx-version-min=10.14 -dynamiclib -Wl,-headerpad_max_install_names  -o /Users/intermodalics/catkin_ws/devel_isolated/geometric_shapes/lib/libgeometric_shapes.dylib -install_name @rpath/libgeometric_shapes.dylib CMakeFiles/geometric_shapes.dir/src/bodies.cpp.o CMakeFiles/geometric_shapes.dir/src/body_operations.cpp.o CMakeFiles/geometric_shapes.dir/src/mesh_operations.cpp.o CMakeFiles/geometric_shapes.dir/src/shape_extents.cpp.o CMakeFiles/geometric_shapes.dir/src/shape_operations.cpp.o CMakeFiles/geometric_shapes.dir/src/shape_to_marker.cpp.o CMakeFiles/geometric_shapes.dir/src/shapes.cpp.o -Wl,-rpath,/opt/ros/kinetic/lib -Wl,-rpath,/usr/local/lib -lassimp.5 /usr/local/lib/libqhull_p.dylib /opt/ros/kinetic/lib/librandom_numbers.dylib /opt/ros/kinetic/lib/libresource_retriever.dylib /opt/ros/kinetic/lib/libroscpp_serialization.dylib /opt/ros/kinetic/lib/librostime.dylib /usr/local/lib/libboost_date_time.dylib /opt/ros/kinetic/lib/libcpp_common.dylib /usr/local/lib/libboost_system.dylib /usr/local/lib/libboost_thread-mt.dylib /usr/local/lib/libconsole_bridge.0.4.dylib /usr/local/lib/libconsole_bridge.0.4.dylib /usr/local/lib/libboost_system-mt.dylib /usr/local/lib/libboost_filesystem-mt.dylib 
ld: library not found for -lassimp.5
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Variable `ASSIMP_LIBRARIES` must not contain only a filename. Why not the name of the imported target, `assimp::assimp`? That should always work independent of the build type, OS and for both, static and shared libraries, given that the `IMPORTED_LOCATION` target property is set correctly with https://github.com/assimp/assimp/pull/2765. Or alternatively `ASSIMP_LIBRARIES` must be set to the full path to the library.

This issue might be related to cmake policy [CMP0060](https://cmake.org/cmake/help/latest/policy/CMP0060.html), but setting it to `NEW` still does not solve the problem.

What is the reason for not letting CMake create these files automatically with [`install(EXPORT ...)`](https://cmake.org/cmake/help/latest/command/install.html#export) as usual? Compatibility with older CMake versions?

**Comment by kimkulling** [comment]
Shall be fixed.
