### ISSUE TITLE
I suppose to simplify the metadata implementation.

### ISSUE THREAD

**Issue by runforu** [assimp/assimp#2939]
The metadata implementation of aiScene is not simple and elegant as metadata should be.
I suggest simplify metadata to only support string and give the right to interpret these value to the user of the library.

Tips: string is a universal type, sometimes it is elegant and simple.

**Comment by runforu** [comment]
In addition, assimp should support category. The category of metadata can be implemented by adding category before the key, default category's metadata "version" looks like a pair of <"default|version", "2.0">

**Comment by RichardTea** [comment]
A change like that would completely break binary _and_ source compatibility, both externally and within assimp itself, which should only be done if absolutely necessary because it immediately puts a huge amount of work onto everyone.

Aside from that, type-safety is very, very important. Conversion to and from strings is very prone to error (and inefficient, but we'll ignore that part)
- Is this a "10" because it's labelled "10", or is it actually the number 10?
- integer or floating point?
- locale and encoding issues (decimal point, exponent, precision loss)
- truthiness ("true", "benar", "wahr" or "1")

The metadata is a variant so callers can determine the actual type (and convert if need be)

There are certainly other, better C++ back-ends to the C interface, (eg the C++17 std::variant).
However, assimp is currently required to support compilers like MSVC2013 that only partially support C++11, so any replacement variant 'back end' would need to be supported there too.

**Comment by runforu** [comment]
String is not inefficient. I close the issue because of compatibility.
