### ISSUE TITLE
header template error at line 100 pi error constant in mathfunctions.h

### ISSUE THREAD

**Issue by harrism76** [assimp/assimp#3310]
I'm using visualstudio 2019 16.3.3 maybe thats my problem, just kidding lol. I'm getting an error for line 100 in mathfunctions.h saying that the template statement is not correct for a constant, i'm not an expert with templates or c++ at the matter but i've read that static_cast is not a value to use in templates or headers and try integral_cast but same error. I know sometimes the compiler throws errors at line 100 when the problem is at line 95 or 99 as an example, but when i comment the template out it compiles. Sometimes i think c++ compatibility as c++11 or c++99 or something, the newer c++ standard is stricter in its checks maybe thats the build fails. I notice 5.0.0 doesn't have PI where 5.0.1 includes this line.
I'm using assimp in this modified project to load meshes into the 3d engine, not sure if that matters or what pi is used for.

https://github.com/GameInstitute/RuntimeMeshLoader

error from assimp compile
Severity	Code	Description	Project	File	Line	Suppression State
Error	C2988	unrecognizable template declaration/definition	RUMTIME_MESH_LOADER	E:\Unreal Projects\RUMTIME_MESH_LOADER\Plugins\RuntimeMeshLoader\ThirdParty\assimp\include\assimp\MathFunctions.h	101	

Severity	Code	Description	Project	File	Line	Suppression State
Error	C2059	syntax error: 'constant'	RUMTIME_MESH_LOADER	E:\Unreal Projects\RUMTIME_MESH_LOADER\Plugins\RuntimeMeshLoader\ThirdParty\assimp\include\assimp\MathFunctions.h	101	

line causing issues
template<class T>
inline T PI() {
	
	return M_PI;
///    return static_cast<T>(3.14159265358979323846);

}

**Comment by BaldricS** [comment]
I happened to get this error, and some googling around landed me on this page. Since it doesn't have an answer I'll go ahead and supply what worked for us in the hopes that it helps some other folks who may land here.

In our codebase, we had a a macro file that had defined `PI` as a constant and this macro was causing the word `PI` to get substituted for a constant float value with basically the same error messages as above.

My recommendation is to please check your codebase (or other externals) for misbehaving macros. Renaming our #define to be K_PI (chosen for reasons internal to the project) instead of PI resolved the issue for us.

Assimp may also want to consider changing the name of the function from PI to something else, because this is probably a fairly common #define that folks like to make.

**Comment by harrism76** [comment]
Thanks for the update!!!! I was going to use assimp as a way to load meshes into epic unreal engine at runtime for gaming. PI is a standard term i think use almost everywhere, like python language probably has pi term in it. Couldn't figure out why visual c++ was complaining about that, normally its code around where the error happens. So this is similar to the C++ standard 99, 11, etc, like a reserved term/keyword used by the compiler or c++ standard.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by kkulling** [comment]
Hi, I guess the easiest way would be to rename it to ai_pi.
