### ISSUE TITLE
Linux build is extremely large

### ISSUE THREAD

**Issue by devvoid** [assimp/assimp#3317]
**Describe the bug**
Linux shared library builds of Assimp are significantly larger than they are on Windows.

With default settings (no edits to the makefile, no options changed):
- GCC, Debug: 133mb.
- GCC, Release: 244mb.
- Windows, Release: 27mb.

**To Reproduce**
1. Download Assimp 5.0.1 source code from the tag.
2. Build using instructions in Build.md
3. Look at the size

**Expected behavior**
Linux builds should be around the same size as the Windows version.

**Desktop (please complete the following information):**
 - OS: Ubuntu 
 - Version 20.04

**Additional context**
None.

**Comment by panmarco83** [comment]
I am having the same issue, but I am seeing `with debug_info` no matter what I do

**Comment by kimkulling** [comment]
I guess this was caused by a misleading debug flag in our debug build. I introduced this into the master some months ago. Aorry for that. Which version do you use? The released version or the latest master. On the latest master this siuue should be fixed already.

As a workaournd: grep for the debug-flag -g in our CMakeLists.txt files and remove this.

**Comment by panmarco83** [comment]
v5.0.1 for me

**Comment by devvoid** [comment]
Released tag here too.

Thanks for the help!

**Comment by devvoid** [comment]
Removing -g reduced it down to 40mb. Problem resolved, thanks!
