### ISSUE TITLE
Building static libs from source, missing aiGetErrorString()

### ISSUE THREAD

**Issue by tim-rex** [assimp/assimp#3379]
Building AssImp from source.
Configured via CMake with `BUILD_SHARED_LIBS` disabled
The resulting .lib appears to be missing `aiGetErrorString()`

1. Download AssImp from source.
2. Configure via CMake with BUILD_SHARED_LIBS unchecked
3. Build the solution via Visual Studio 2019
4. From an external project, with a call to `aiGetErrorString()`, link against the newly created static library via `#pragma comment(lib, "assimpd.lib")`
`
5. Build the external project
6. Observe a link error, regarind an unresolved external symbol for `aiGetErrorString`

**Expected behavior**
The statically linked assimpd.lib should include `aiGetErrorString()`

**Desktop:**
 - Windows 10
 - Visual Studio 2019 v16.7.2

Dynamically linking does not appear to be an issue.

**Comment by kimkulling** [comment]
There is no rule to remove this API call from the static lib. How have you looked for the symbol?

**Comment by tim-rex** [comment]
I didn't go looking for it explicitly, I just took the linkers word for it at face value.
I worked around it by dynamically linking instead.

**Comment by kimkulling** [comment]
After a lot of redesign, I opened https://github.com/assimp/assimp/pull/3415 to reproduce your behavior. It worked on my machine. I added one test for you to be able that with the current master this issue is gone: just create a static-linked installation and run the unit tests form master shall help you to reproduce your issue.
