### ISSUE TITLE
X3D Parser removed by "3MF: Migration"

### ISSUE THREAD

**Issue by gkv311** [assimp/assimp#3646]
I've wanted to check one issue with X3D import (experienced on Assimp 5.0) in development branch, but instead just realized the whole X3D parser being removed by "3MF: Migration" commit of @kimkulling a half a year ago : 7e93ae4428c522dabc0778f68fd7705e034344b8

I guess there was some attempt to rewrite XML parsers in the project, but for some reason rewriting X3D parser was just stopped at removal step (I've tried to convert some X3D files in hope that I just don't understand how reader works now, but result was just a blank output file without any error message).

The commit is not associated with any pull request, where one could find some discussion about plans, so I was unable to find any details on this topic. If this is "under control", it would be nice putting some TODO message in code and report an error message on attempt to use this import plugin...

**Comment by kimkulling** [comment]
Hi,

correct, at this moment the X3D-parser is not in the development branch. I will do a rewrite of the X3D-Import because it took much to much time to get it done within the xml-migration. The concepts of irrXml and pugi_xml are completly different. I need to check if I forget to add an issue for that. Until this job is done please use the older release. 
I am really sorry about this confusion. When I finished the migration I was a littl ebit tired after a coulpe of sleepless nights to get th emigration done. 

We got a big number of fuzzer-issues by the old xml-parser and this was the reason for me to switch to a new parser.

Kim

**Comment by gkv311** [comment]
Thanks for clarifying!

**Comment by kimkulling** [comment]
PLease check https://github.com/assimp/assimp/issues/3647
