### ISSUE TITLE
PBRT exporter crashes when scene meta data is null.

### ISSUE THREAD

**Issue by JC3** [assimp/assimp#3781]
Library version: master @ cd42b99
Platform: Windows 10 64-bit
Compiler: MSVC 2019 64-bit

When the "pbrt" exporter is used to export an aiScene whose pMetaData member is null, it crashes at https://github.com/assimp/assimp/blob/master/code/Pbrt/PbrtExporter.cpp#L176. 

The stack trace...

```
1  Assimp::PbrtExporter::WriteMetaData PbrtExporter.cpp 176 0x7ff8a7c2521a 
2  Assimp::PbrtExporter::PbrtExporter  PbrtExporter.cpp 155 0x7ff8a7c244bc 
3  Assimp::ExportScenePbrt             PbrtExporter.cpp 104 0x7ff8a7c47545 
4  Assimp::Exporter::Export            Exporter.cpp     495 0x7ff8a7273308 
5  Assimp::Exporter::Export            Exporter.hpp     504 0x7ff684e49c71 
```

...indicates that it just never checks to see if it's null before checking mNumProperties.

It should probably treat null meta data the same as meta data with 0 properties.

Since it appears to be the only exporter that cannot handle this case, I am interpreting it as a bug in the exporter.

**Comment by kimkulling** [comment]
Thanks for the report and the fix 👍

**Comment by lucasc190** [comment]
I'm a little confused - this issue was closed as completed, but as far as I can tell, the bug is still present. I noticed the same thing with issue #3783.

For now, I am working around this bug by ensuring that an empty metadata object is included when there is no metadata.

Yours sincerely,
Lucas Cardellini
