### ISSUE TITLE
obj file has no material information，but scene has 

### ISSUE THREAD

**Issue by kingui1106** [assimp/assimp#3832]
I use assimp_cmd project. use info read a obj file.Then, i found it have nummaterial.
my code is  The 5.0.1 bugfix release.

Below is my obj file

> v  -0.2583 -4.2958 4.0252
v  0.3480 -3.9487 3.7600
v  0.2024 -3.6995 4.1700
g sdsd
f 1 2 3

**Comment by JC3** [comment]
This is by design. All aiMesh's must reference a valid material. Therefore, for all file formats, if the imported data does not have a material, assimp will add a default material ([source](https://github.com/assimp/assimp/blob/8f0c6b04b2257a520aaab38421b2e090204b69df/code/Common/ScenePreprocessor.cpp#L69-L91), via [here](https://github.com/assimp/assimp/blob/8f0c6b04b2257a520aaab38421b2e090204b69df/code/Common/Importer.cpp#L675-L676).

**Comment by kimkulling** [comment]
That is correct.
