### ISSUE TITLE
Please make a release

### ISSUE THREAD

**Issue by yurivict** [assimp/assimp#3948]
**Describe the bug**
There were some fixes made, like fixing build on i386, etc.

**Comment by arturred** [comment]
Is it possible to also publish assets with Windows x86 and x64 dll-s using VS release (2013, 2015, or 2017)?

**Comment by kimkulling** [comment]
Let's see. I will change my job. So I will have one month free. Hopefully this will help to increase our development speed.

**Comment by Neumann-A** [comment]
+1. qtquick3d in Qt6 also needs a newer version of assimp so having a new release tag would be nice.

**Comment by krop** [comment]
I'm facing the same issue in openSUSE. I'm holding qtquick3d until I can use an assimp release.

**Comment by abenedik** [comment]
I am also asking for a new release. The problem that I have is that there were some breaking changes in the core structs and therefore the .Net wrappers (and probably wrappers in some other languages) do not work anymore. 

For example, on May 3 2021 Mesh.h was changed by adding mTextureCoordsNames (https://github.com/assimp/assimp/commit/f91b439f79cc106f08678a265562191c67b184cf). This means that when converting the native Mesh into .Net Mesh, the layouts of the structs no longer match and this crashes the wrapper.

Because the version of Assimp library is still 5.0.1 it is not possible to update the .Net wrapper that would be able to distinguish between Assimp with older Mesh struct and Assimp with new mesh struct. Having a new version of Assimp would provide a way to solve that.

To prevent such problems in the future, I would also suggest implementing some kind of automatic versioning system - for example, the build version number may be increased each day from the last official release or on each commit from the last official build. This way it would be possible to distinguish Assimp builds that are made between official releases.

**Comment by kimkulling** [comment]
Hi, I was thinking about this, too. We got so many changes in the pastm that is gets harder and harder to release useful versions.

So instead of releasing minor versions manually we can release them on a monthly base.

Any other opinions?

**Comment by RichardTea** [comment]
I'm also seeing more duplicate bug reports being created for things that were broken in the 5.0.1 release but are now long fixed in current development.
Worse, it's getting really difficult to figure out whether a bug report refers to current development at all.

Keeping full binary compatibility between versions is really, really difficult, and basically impossible for "other-language" wrappers as they need to update to match whenever any fields are added - even if the 'raw C' interface is otherwise compatible, the C++ interface often won't be - if only because there's so many C++ ABIs to choose from!

I agree, it makes sense to do monthly semi-automatic releases - with the option to skip making a release if a significant issue is found.

I'd recommend the following basis:
- Patch release: There are no known changes to the public C/C++ ABI.
 Contains internal bugfixes only.
- Minor release: There are known changes to the public C/C++ ABI that are likely to be C & C++ source-compatible
  - Applications are unlikely to need code changes
  - Applications are likely to need to be recompiled & language wrappers updated
  - Custom cmake configs _may_ need to be updated
  - Supporting libraries may have been changed
- Major release: Significant API changes that are very likely to require application code changes.

The Patch could be auto-incremented.
The Minor and Major increments would have to be done manually by looking at the PRs and adding the increment if needed.

I think it'd be good to just set a date when this will happen - how about Halloween?

**Comment by kimkulling** [comment]
Ha! https://github.com/assimp/assimp/pull/4170

**Comment by ZombieRaccoon** [comment]
@kimkulling I'm glad it has finally come together! May I ask what your plans are regarding a stable release? I'm in the process of submitting the release candidate to [Conan](https://github.com/conan-io/conan-center-index/pull/8008), but they'd prefer to take a stable version if it wasn't too far ahead.

**Comment by kimkulling** [comment]
Finally: https://github.com/assimp/assimp/releases/tag/v5.1.0

I was just trying to get some X3D-related issues closed before.

**Comment by kimkulling** [comment]
I will try to release a patch release each week. Every time when we will get an update for our API I will release a minor version instead. Next steps for me: autogenerate installer packages and copy the documentation automatically as well.
