### ISSUE TITLE
Bug: Cross-compile fails

### ISSUE THREAD

**Issue by PQCraft** [assimp/assimp#4214]
I am attempting to cross-compile assimp for Windows due to the lack of binaries (:moyai: every other library in existence just has the drag & drop archive for MinGW which includes the lib/ and include/ directories)
I have added `-O2` and `-Wa,-mbig-obj` to `CMAKE_CXX_FLAGS` and `CMAKE_C_FLAGS` yet it always fails with
```
/usr/lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/as: CMakeFiles/assimp.dir/Importer/StepFile/StepFileGen1.cpp.obj: section .xdata$_ZNSt11_Tuple_implILy1EJSt14default_deleteIN6Assimp8StepFile27definitional_representationEEEE7_M_headERS5_: string table overflow at offset 10000047
/tmp/ccGDovGj.s: Assembler messages:
/tmp/ccGDovGj.s: Fatal error: CMakeFiles/assimp.dir/Importer/StepFile/StepFileGen1.cpp.obj: file too big
make[2]: *** [code/CMakeFiles/assimp.dir/build.make:2512: code/CMakeFiles/assimp.dir/Importer/StepFile/StepFileGen1.cpp.obj] Error 1
make[1]: *** [CMakeFiles/Makefile2:310: code/CMakeFiles/assimp.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```
I am using Arch Linux with `x86_64-w64-mingw-gcc`/`x86_64-w64-mingw-g++` 11.2.0

**Comment by kimkulling** [comment]
Feel free to post a PR to get the pre-compiled libs automatically. Unfortunately, I am doing this next to my job and my family and I am lack on time.

The problem you are facing shall be fixed on 5.1.1. Which version do you use?

**Comment by PQCraft** [comment]
@kimkulling I cloned the source of 5.0.1

**Comment by PQCraft** [comment]
Also I would try looking in to GitHub actions as AFAIK you can basically run scripts to build the binaries and edit the release and attach the files. IIRC this can't be done with pull requests though and must be set up by the repo maintainer.

**Comment by PQCraft** [comment]
I ended up downloading an AUR package (`mingw-w64-assimp`) which compiled fine and I went into `/usr/x86_64-w64-mingw32/` and copying the includes and libraries into the MinGW installation under WINE.

**Comment by PQCraft** [comment]
Link to the PKGBUILD: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=mingw-w64-assimp

**Comment by kimkulling** [comment]
We are currently at version 5.1.2. So this stuff shall be fixed right now. I would be really happy if you could check whether the deviations are still there.

And some words about our CI-chain:
For sure we are using the Github-actions (for instance you can see here which kind of stuff we are testing: https://github.com/assimp/assimp/actions/runs/1509512209). We are testing the lib for different platforms are we are using a lot of sanitizers to make sure that we don't have any leaks, undefined behaviors, or different kinds of bugs. What is currently missing is the generation for all the different platforms people are looking for. Because people are using this for a lot of different platforms.

So the different providers for packages are providing their own builds. Hopefully, I will be able to find the time to help you here as well. But right now I don't have this ready. Sorry for that!

Kim

**Comment by PQCraft** [comment]
@kimkulling :+1: Will test once I get some free time today. My computer is fairly weak and GCC causes the system to lag and/or freeze so I will test when I have nothing to do.

**Comment by kimkulling** [comment]
That would be really reat. I am looking forward for your feedback!
