### ISSUE TITLE
Missing installed cpp macros that define the assimp version

### ISSUE THREAD

**Issue by rhabacker** [assimp/assimp#4291]
**Is your feature request related to a problem? Please describe.**
As mentioned at https://github.com/vsg-dev/vsgXchange/issues/65#issuecomment-1000339888, there are currently no cpp macros that define the assimp version used. If an application that uses assimp requires version-specific code, appropriate support is required at the build system level of the application.

**Describe the solution you'd like**
It would be helpful if assimp would provide appropriate macros e.g. in an installed version.h file which is filled by cmake with the current values by calling `configure_file()`, something like: 

version.h.cmake: 
```
..
#define ASSIMP_MAKE_VERSION(major, minor, patch) ((((uint32_t)(major)) << 22) | (((uint32_t)(minor)) << 12) | ((uint32_t)(patch)))

#define ASSIMP_VERSION_MAJOR @ASSIMP_VERSION_MAJOR@
#define ASSIMP_VERSION_MINOR @ASSIMP_VERSION_MINOR@
#define ASSIMP_VERSION_PATCH @ASSIMP_VERSION_PATCH@
#define ASSIMP_VERSION ASSIMP_MAKE_VERSION(ASSIMP_VERSION_MAJOR, ASSIMP_VERSION_MINOR, ASSIMP_VERSION_PATCH)
#define ASSIMP_VERSION_STRING "@ASSIMP_VERSION_MAJOR@.@ ASSIMP_VERSION_MINOR@.@ASSIMP_VERSION_PATCH@"
...
```
In client code, the following fragment can then be used to select version-specific code
```
#if ASSIMP_VERSION >= ASSIMP_MAKE_VERSION(5, 1, 0)
   // add 5.1 code
#else
   // add code for other version
#endif
```

**Describe alternatives you've considered**
The alternative of not adding this support requires each client package to add support itself, which is additional overhead.

**Comment by kimkulling** [comment]
Sorry for that. I haven't created a test case for that feature. This will get fixed as fast as possible.

**Comment by kimkulling** [comment]
I have just checked it. You need to recreate revision.h by rerun the CMake run. Then the macros are defined in the expected way.

**Comment by ofTheo** [comment]
Is there any way to know what version of assimp is being included from assimp 3 to assimp 5 using preprocessor macros?

We have an open source project which uses assimp and some of the platforms it is just using the version that comes with the OS. So it can be assimp 3 or 4 or 5.  

We would like to include the assimp 5 features but guard them with #ifdef or `#if ASSIMP_VERSION_MAJOR >= 5 && ASSIMP_VERSION_MINOR >= 1` so that our code can be backwards compatible. 

I see that we could copy `revision.h` into the includes folder when building locally but this doesn't solve it for system installed versions of assimp. 

I am guessing there isn't a macro that can be queried as the other poster mentioned. 
But going forward it would make a lot of sense if something like `ASSIMP_VERSION_MAJOR` existed in `version.h`

Thanks!
Theo
