### ISSUE TITLE
glTF2 Importer uses incorrect code to calculate horizontal FOV

### ISSUE THREAD

**Issue by jamesn031199** [assimp/assimp#4435]
The [importer code](https://github.com/assimp/assimp/blob/master/code/AssetLib/glTF2/glTF2Importer.cpp#L846) for glTF2.0 assumes multiplying the vertical FOV by the aspect ratio is how horizontal FOV is calculated.
However, this is not correct and the correct way to convert between the two is by [this method](https://i.imgur.com/mz5NpQu.png) referenced in [this Reddit post](https://www.reddit.com/r/Planetside/comments/1xl1z5/brief_table_for_calculating_fieldofview_vertical/).

**Comment by kvnnap** [comment]
This [code ](https://github.com/assimp/assimp/blob/aae93691b9923e13af089a2a092fdd75bbfab489/code/AssetLib/glTF2/glTF2Importer.cpp#L911C20-L911C35)does not respect the aiCamera's interface. It computes the correct horizontal FOV, however, the camera struct `aiCamera` [mHorizontalFOV](https://github.com/assimp/assimp/blob/aae93691b9923e13af089a2a092fdd75bbfab489/include/assimp/camera.h#L144C6-L144C6) is defined as being **half** the horizontal field of view according to the documentation. I have noticed this issue since when I import FBX files the cameras load properly, however with gltf2 the FOV is always wrong. I tested a scene with cameras in this [online gltf viewer](https://gltf-viewer.donmccurdy.com/), and indeed they load fine here. Additionally, I checked the FBX importer code [here](https://github.com/assimp/assimp/blob/aae93691b9923e13af089a2a092fdd75bbfab489/code/AssetLib/FBX/FBXConverter.cpp#L449C34-L449C34). This code computes half the horizontal FOV as seen below:

```c++
// FBX fov is full-view degrees. We want half-view radians.
out_camera->mHorizontalFOV = AI_DEG_TO_RAD(fov_deg) * 0.5f;
```

The code [here](https://github.com/assimp/assimp/blob/aae93691b9923e13af089a2a092fdd75bbfab489/code/AssetLib/glTF2/glTF2Importer.cpp#L911C17-L911C17) should therefore change from:

```c++
aicam->mHorizontalFOV = 2.0f * std::atan(std::tan(cam.cameraProperties.perspective.yfov * 0.5f) * ((aicam->mAspect == 0.f) ? 1.f : aicam->mAspect));
```

to 

```c++
aicam->mHorizontalFOV = std::atan(std::tan(cam.cameraProperties.perspective.yfov * 0.5f) * ((aicam->mAspect == 0.f) ? 1.f : aicam->mAspect));
```

I will gladly provide a pull request if this is agreed to be correct.
