### ISSUE TITLE
Bug: FBX export gives wrong animation duration 

### ISSUE THREAD

**Issue by TwnKey** [assimp/assimp#4698]
Hello, 
I noticed the animations in my exported fbx files were stopping before the actual end of the animation, leaving some keys behind. 
I believe this is due to this specific part of the code here in code/AssetLib/FBX/FBXExporter.cpp: 
![image](https://user-images.githubusercontent.com/69110695/185710695-1fa02135-5c63-46da-bfc7-d98e2e676494.png)
which causes the duration to be floored right before converting to k time units (if I understood correctly), losing the fractional part.

I changed it to this to make it work for my project:
![image](https://user-images.githubusercontent.com/69110695/185710977-c6bd8531-7d63-482d-be44-a510cfd83928.png)

**Comment by Nor-s** [comment]
Did you change the transformation key times too?

```cpp
// position/translation
            for (size_t ki = 0; ki < na->mNumPositionKeys; ++ki) {
                const aiVectorKey& k = na->mPositionKeys[ki];
                times.push_back(to_ktime(k.mTime));
```
`to_ktime(k.mTime)`  => `to_ktime(k.mTime, anim)`

it is work for my project.

And I did some tests fbx exporter only export 24fps(FileGlobalSettings::FrameRate_CINEMA).
So the duration can be unstable.

**Comment by TwnKey** [comment]
Ah no, I didn't, I actually didn't even think about doing it. I know the k_time function with only the time as argument works too. 
But now I'm wondering if I really should, I was under the impression that k_time is only used for fbx, so if I wanted to change the export format to dae (or make the user able to change it to dae), would it make sense to use k_time before the export function is called? 
I believe the conversion itself is harmless but if the k_time is only intended for fbx I would prefer to keep the key time agnostic of any format if possible.

**Comment by Nor-s** [comment]
What I meant was the conversion inside the fbx export function. not before the export function.

[FBXExporter.cpp](https://github.com/assimp/assimp/blob/04997ccbf3db5e1fa5f54478980896d74c3d08db/code/AssetLib/FBX/FBXExporter.cpp#L2417)

If you use the `ktime(time)` function in FBXExporter.cpp, you can see that the scale is different from the duration.  
(my case is fbx to fbx. In other cases, I don't know.)

The problem seems to occur because the FBX importer uses the same formula for duration and ktime, but the FBX exporter uses different formulas.

-  [import::Converter::duration](https://github.com/assimp/assimp/blob/04997ccbf3db5e1fa5f54478980896d74c3d08db/code/AssetLib/FBX/FBXConverter.cpp#L2709), [import::Convert::mTime](https://github.com/assimp/assimp/blob/04997ccbf3db5e1fa5f54478980896d74c3d08db/code/AssetLib/FBX/FBXConverter.cpp#L3219)
    ```cpp
    CONVERT_FBX_TIME(start_time) * anim_fps
    ```

- [export::duration](https://github.com/assimp/assimp/blob/04997ccbf3db5e1fa5f54478980896d74c3d08db/code/AssetLib/FBX/FBXExporter.cpp#L2322)
  ```cpp
  p.AddP70time("ReferenceStop", to_ktime(anim->mDuration, anim));
  ```

- [export::time](https://github.com/assimp/assimp/blob/04997ccbf3db5e1fa5f54478980896d74c3d08db/code/AssetLib/FBX/FBXExporter.cpp#L2431)
  ```cpp
  times.push_back(to_ktime(k.mTime));
  ```
