### ISSUE TITLE
Bug: Assimp (.Net) merges vertices

### ISSUE THREAD

**Issue by Raildex** [assimp/assimp#4834]
**Describe the bug**
Assimp merges vertices together.

**Expected behavior**
The vertex count should be identical to the input.

**Screenshots**
![image](https://user-images.githubusercontent.com/14938934/206697613-ec0aff2f-a014-495c-be81-4b9a1e9581a2.png)

**Platform (please complete the following information):**
 - OS: Windows 10, AssimpNet

**Comment by Saalvage** [comment]
I know this issue is pretty old, but:
1. I'm fairly certain Assimp.Net is unfortunately no longer officially supported, so if this is not reproducible in the main library then I doubt it will get fixed.
2. Without the entire model file (and mabye the code) you're getting this behavior with it's likely impossible to reproduce or fix this.
3. Are you sure this is not a case of [this](https://www.gamedev.net/forums/topic/633306-assimp-number-of-vertices/)? (linked to in the [FAQ](https://github.com/assimp/assimp/wiki/FAQ))
