### ISSUE TITLE
assimp_cmd build fails under cygwin

### ISSUE THREAD

**Issue by aemxdp** [assimp/assimp#489]
I'm trying to build full assimp via cygwin this way:

```
cd assimp
cmake .
make
```

And this is what I get:

```
Scanning dependencies of target assimp_cmd
[ 79%] Building RC object tools/assimp_cmd/CMakeFiles/assimp_cmd.dir/assimp_cmd.rc.obj
/usr/bin/windres: invalid option -f

tools/assimp_cmd/CMakeFiles/assimp_cmd.dir/build.make:54: recipe for target 'tools/assimp_cmd/CMakeFiles/assimp_cmd.dir/
assimp_cmd.rc.obj' failed
make[2]: *** [tools/assimp_cmd/CMakeFiles/assimp_cmd.dir/assimp_cmd.rc.obj] Error 1
CMakeFiles/Makefile2:156: recipe for target 'tools/assimp_cmd/CMakeFiles/assimp_cmd.dir/all' failed
make[1]: *** [tools/assimp_cmd/CMakeFiles/assimp_cmd.dir/all] Error 2
Makefile:117: recipe for target 'all' failed
make: *** [all] Error 2
```

After some googling and looking into makefiles it seems to be some problem with RC_FLAGS or RC_DEFINES here:

```
/usr/bin/windres.exe  -O coff $(RC_FLAGS) $(RC_DEFINES) /cygdrive/c/Users/apsk/Downloads/assimp/tools/assimp_cmd/assimp_cmd.rc CMakeFiles/assimp_cmd.dir/assimp_cmd.rc.obj
```

I'm not sure if this is a bug or maybe I'm just doing something wrong.

**Comment by kimkulling** [comment]
Seems to be a bug. Thanks for the report!

**Comment by aru** [comment]
Could this be fixed by preventing windres.exe from being called with the -fIPC flag? I'm not sure the -fvisibility flag is supported either...

`tools/assimp_cmd/CMakeFiles/assimp_cmd.dir/build.make:56:       cd /home/Aru/bii/assimp-3.1.1/tools/assimp_cmd && /usr/bin/windres.exe  -O coff $(RC_FLAGS) $(RC_DEFINES) /home/Aru/bii/assimp-3.1.1/tools/assimp_cmd/assimp_cmd.rc CMakeFiles/assimp_cmd.dir/assimp_cmd.rc.obj`

`tools/assimp_cmd/CMakeFiles/assimp_cmd.dir/flags.make:10:RC_FLAGS =   -I/home/Aru/bii/assimp-3.1.1 -I/home/Aru/bii/assimp-3.1.1/include -I/home/Aru/bii/assimp-3.1.1/code/BoostWorkaround -I/usr/include -I/home/Aru/bii/assimp-3.1.1/code`    **-fPIC -fvisibility=hidden -Wall**

**Comment by kimkulling** [comment]
Could you please test this and create a patch / pull request? I don't have a cygwin-environment here.

Thanks a lot,
Kimmi

**Comment by aru** [comment]
Sure,  I'll give it a spin tomorrow.

~Albin

**Comment by aru** [comment]
Hi Kim,

I have successfully compiled assimp, assimp_cmd and assimp_view, fix is a bit more involved, however:
First the trivial stuff:
- Just substitute add_definitions() with set()
set(CMAKE_CXX_FLAGS "-fPIC") # this is a very important switch and some libraries seem now to have it....

However, as cygwin makes the project believe it is a Unix system and takes standard unix makefiles, we have to change code/ByteSwap.h's filename as case-insensitive windows tries to include this ByteSwap.h file instead of the system's byteswap.h when including system's endian.h. This results in tons of other compiling issues.

In my fix I simply renamed ByteSwap.h to AIByteSwap.h and everything compiled. 
1. Do I have permission to rename this file?
2. What should the filename be?

**Comment by acgessler** [comment]
Please rename  it to `ByteSwapper.h`.

**Comment by aru** [comment]
ok done :)

https://github.com/assimp/assimp/pull/544

**Comment by kimkulling** [comment]
Already fixed, I will closed this one.
