### ISSUE TITLE
Create UTF-8 counterparts for UTF-16 test models (PR ready to merge)

### ISSUE THREAD

**Issue by tellypresence** [assimp/assimp#5015]
Seems like there's a lot of breakage in loading UTF-16 models of various formats the last few years.

The trouble is that if a test model bundled with assimp is only available as UTF-16, when breakage occurs it won't be known whether the loader actually broke, or just stopped supporting UTF-16.

To improve the situation, if UTF-16 models were to be converted to UTF-8 and added to the repo alongside their UTF-16 counterparts, then unit tests would detect format vs loader breakage more readily.

**Comment by turol** [comment]
No, the better fix would be to add a UTF-16 to UTF-8 conversion to loading and add all the models to unit tests to make sure they stay working.

**Comment by turol** [comment]
Actually it looks like pugixml is supposed to automatically handle unicode
https://pugixml.org/docs/manual.html#dom.unicode
https://pugixml.org/docs/manual.html#loading.encoding
I wonder why it doesn't seem to work correctly for us.

**Comment by turol** [comment]
https://github.com/assimp/assimp/blob/5a4f7c0a375fd2acc3bda9414d21efe711346ede/include/assimp/XmlParser.h#L305
`load_string` does not do unicode conversion.
https://github.com/assimp/assimp/blob/5a4f7c0a375fd2acc3bda9414d21efe711346ede/contrib/pugixml/src/pugixml.hpp#L1067
Should use either stream loader or `load_buffer`/`load_buffer_inplace` since we already read it into a buffer.

**Comment by tellypresence** [comment]
PR #5017 will address this

**Comment by kimkulling** [comment]
Closed by  https://github.com/assimp/assimp/pull/5017
