### ISSUE TITLE
Brew install issues on OSX

### ISSUE THREAD

**Issue by algomusic** [assimp/assimp#507]
Mac OSX 10.6.8, assimp 3.1.1
Brew install fails (as below) - any suggestions?

017320:~ s978684$ brew install assimp
==> Downloading https://downloads.sourceforge.net/project/assimp/assimp-3.1/assimp-3.1.1_no_test_mod
Already downloaded: /Library/Caches/Homebrew/assimp-3.1.1.zip
==> cmake . -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/assimp/3.1.1 -DCMAKE_BUILD_TYPE=None -DCMAKE_FI
==> make install
/tmp/assimp20150322-8709-ct5t3t/assimp-3.1.1/code/FBXMeshGeometry.cpp:510: note: synthesized method ‘Assimp::Formatter::basic_formatter<char, std::char_traits<char>, std::allocator<char> >::basic_formatter(const Assimp::Formatter::basic_formatter<char, std::char_traits<char>, std::allocator<char> >&)’ first required here 
make[2]: *** [code/CMakeFiles/assimp.dir/FBXMeshGeometry.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [code/CMakeFiles/assimp.dir/all] Error 2
make: *** [all] Error 2

**Comment by doughazell** [comment]
I had the same problem trying to install Indigo version of ROS (http://wiki.ros.org/indigo/Installation/OSX/Homebrew/Source) on Snow Leopard (10.6.8) which manifested by running 'rosdep install --from-paths src --ignore-src --rosdistro indigo -y' so solved it by installing assimp 3.0:
1) $ brew edit assimp
  url "http://sourceforge.net/projects/assimp/files/assimp-3.0/assimp--3.0.1270-source-only.zip"
  version "3.0.255"

(NOTE: The version chosen as '3.0.255' will become clear later)

2) $ brew install assimp
==> Downloading http://sourceforge.net/projects/assimp/files/assimp-3.0/assimp--3.0.1270-source-only.zip
==> Downloading from http://kent.dl.sourceforge.net/project/assimp/assimp-3.0/assimp--3.0.1270-source-only.zip
######################################################################## 100.0%
Error: SHA1 mismatch
Expected: d7bc1d12b01d5c7908d85ec9ff6b2d972e565e2d
Actual: e80a3a4326b649ed6585c0ce312ed6dd68942834

3) Change the SHA1 specified version in the brew by:
  $ brew edit assimp
  sha1 "e80a3a4326b649ed6585c0ce312ed6dd68942834"

4) $ brew install assimp
==> Downloading http://sourceforge.net/projects/assimp/files/assimp-3.0/assimp--3.0.1270-source-only.zip
==> Downloading from http://kent.dl.sourceforge.net/project/assimp/assimp-3.0/assimp--3.0.1270-source-only.zip
######################################################################## 100.0%
==> cmake . -DCMAKE_C_FLAGS_RELEASE= -DCMAKE_CXX_FLAGS_RELEASE= -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/assimp/3.0.1264 -DCMAKE_BUILD_TYPE=Relea
==> make install
ld: malformed version number: 3.0.1264

http://sourceforge.net/p/assimp/discussion/817654/thread/381fa18a

..but that was for XCode so small adaption required pour moi...

5) Adapt the download brew bundle to solve linker errors
  $ cd /Library/Caches/Homebrew/
  $ unzip assimp-3.0.255.zip
  $ cd assimp--3.0.1270-source-only
  $ vi CMakeLists.txt
    Alter the revision number into an allowable range:
    #set (ASSIMP_SV_REVISION 1264)
    set (ASSIMP_SV_REVISION 255)
  $ cd ..
  $ zip -r assimp-3.0.255.zip assimp--3.0.1270-source-only/

6) $ brew install assimp
==> Downloading http://sourceforge.net/projects/assimp/files/assimp-3.0/assimp--3.0.1270-source-only.zip
Already downloaded: /Library/Caches/Homebrew/assimp-3.0.255.zip
Error: SHA1 mismatch
Expected: e80a3a4326b649ed6585c0ce312ed6dd68942834
Actual: 7b5b56b29a92ddf09717e492156042f6ba41a11c
Archive: /Library/Caches/Homebrew/assimp-3.0.255.zip

The zip file contents have been changed so that the SHA1 also needs to be updated:

7) $ brew edit assimp
  sha1 "7b5b56b29a92ddf09717e492156042f6ba41a11c"

8) $ brew install assimp
==> Downloading http://sourceforge.net/projects/assimp/files/assimp-3.0/assimp--3.0.1270-source-only.zip
Already downloaded: /Library/Caches/Homebrew/assimp-3.0.255.zip
==> cmake . -DCMAKE_C_FLAGS_RELEASE= -DCMAKE_CXX_FLAGS_RELEASE= -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/assimp/3.0.255 -DCMAKE_BUILD_TYPE=Releas
==> make install
/usr/local/Cellar/assimp/3.0.255: 52 files, 7.0M, built in 11.5 minutes

The SHA1 values may need to be adapted based on your results but you get the process.
