### ISSUE TITLE
Is there a way to only load (specific) embedded textures?

### ISSUE THREAD

**Issue by dbs4261** [assimp/assimp#5736]
Hi folks, I've been working with some very large models (4+ GB) in the GLB format that have embedded textures. I would like to take one pass through the file and only load the meshes, do my processing on them, then open up the required texture files when needed later on. Ideally I would like to load specific textures, for example if I am slicing a mesh, I won't need to access textures that only cover the discarded portion. I've been tinkering with using `AI_CONFIG_PP_RVC_FLAGS` to discard the components I don't need. Correct me if I am wrong, but this only excluded those components from the pre-processing steps, the entire scene is still loaded initially, right? What is the proper way to configure the importer for only reading specific textures?

**Comment by tellypresence** [comment]
Embedded textures are binary blobs within the 3D model file, they don't get extracted automatically -- your implementation code needs to iterate through the embedded textures and convert the blobs to images for applying the textures.  So in that sense if you are able to figure out which textures you need based on their names you would be able to avoid loading them in your own implementation code depending on what mesh-fu you're doing.

But if you are saying you wish to avoid loading an entire 4GB file into memory because it's heavy with embedded textures you won't necessarily be using, it may not be possible to easily do that

**Comment by dbs4261** [comment]
Is there a way to get the offset of those binary blobs from Assimp and access them later? And do the RVC_FLAGS skip the loading of those components, or do they get loaded automatically and then removed before further processing?

**Comment by tellypresence** [comment]
Good news/bad news...the good news is that all the information you need is in the assimp repo.  The bad news is there's not a central page documenting how to access embedded textures; the information is spread around in issues, code comments etc.

Suggest starting with search for "embedded textures" in assimp repo, you'll find issues like these:
- #408
- #1830

**Comment by kimkulling** [comment]
And you can check this: https://medium.com/realtime-rendering-for-fun/assimp-hacks-5-embedded-textures-23e65bbf5d76?sk=3c9ee77ec58845d74269899ddd0cbaeb
