### ISSUE TITLE
Support loading VRML97 (.wrl) and "Classic VRML" (.x3dv) 3D model files

### ISSUE THREAD

**Issue by tellypresence** [assimp/assimp#5862]
X3D is a superset of both VRML97 (`.wrl`) and "Classic VRML" (`.x3dv`) files.  The main difference is in the syntax/format of the files; X3D uses `.xml` while the others are based on the older VRML format.

Since the contents all three formats are understood by X3D, by simply converting the VRML syntax to `.xml`, both `.wrl` and `x3dv` files should be able to be loaded by the current `X3DImporter` class.

**Comment by npolys** [comment]
tihe file encoding is reflected in the file extension:

.wrl is VRML

.x3dv is VRML encoding
.x3d is the XML encoding
.x3db is the binary encoiding

Numerous examples are online,
 transcoded and published nightly:
https://www.web3d.org/x3d/content/examples/X3dResources.html#Examples
X3D Resources<https://www.web3d.org/x3d/content/examples/X3dResources.html#Examples>
Conversions and Translation Tools. Numerous conversion tools are available for the various encodings of X3D and VRML. X3D is a direct superset of VRML with three encodings: XML encoding (.x3d), Classic VRML encoding (.x3dv) and VRML97 encoding (.wrl).X3D is designed so that all three encodings are equivalent, you can choose to use any of them.
www.web3d.org

for example:
https://www.web3d.org/x3d/content/examples/X3dForWebAuthors/

and MIME types are registered w ICANN:
Encoding
File Extension
MIME Type
X3D XML
.x3d, .x3dz
model/x3d+xml
X3D JSON
.x3dj, .x3djz
model/x3d+json
X3D Classic VRML
.x3dv, .x3dvz
model/x3d+vrml
VRML
.wrl, .wrz
model/vrml



________________________________
