### ISSUE TITLE
.travis.yml restricts builds to master branch, making it hard for contributors to verify changes

### ISSUE THREAD

**Issue by LegalizeAdulthood** [assimp/assimp#590]
Maybe I'm just being thick about git, but since the `.travis.yml` file restricts builds to the `master` branch of the repository, there isn't an easy way for a contributor to check their travis build on their forked repository without pushing to their own master.  However, it is more typical to work on a feature branch and submit a pull request from that feature branch.

Is there some reason we can't have travis enabled for all branches?  All the workarounds I can think of for my own contributions are clunky:

1. push to forked master
1. edit `.travis.yml` to contain the name of my short-lived feature branch and rely on myself or the repository owner to strip out this branch name before/when merging

**Comment by kimkulling** [comment]
I guess we had this option in the past. But it was disabled because the build icon on our project-side shows all build results, even for feature branches. 

We can try to show the active build status for the master branch on th project side and enable the travis-stuff for all feature branches, if this is possible.

**Comment by LegalizeAdulthood** [comment]
I used #2 for my travis-oriented pull request

**Comment by kimkulling** [comment]
Deprecated ...
