### ISSUE TITLE
Double precision support

### ISSUE THREAD

**Issue by kimkulling** [assimp/assimp#638]
Hi,
I am trying to import an .obj file that contains some geo-referenced model. All vertices are defined with an absolute offset (no mesh transformation) and because of that, the vertices coordinates are very big, for instance:
v 1024199.614999999 6280752.805999999 0.9109999999890448
Now, the .obj parser, but also the resulting imported mesh, store the data in arrays of aiVector3D, which is defined as follow:
typedef aiVector3t<float> aiVector3D;
I would like all the import pipeline to read my values (at least the vertices position) using double precision floating points.
I guess I will have to hack the source at some locations, but before I start this, I would like to check with you guys if there was a better existing method ?
Thanks a lot,
Greg

**Comment by r-chris** [comment]
If I understand correctly, you made a branch to tackle this problem here:
https://github.com/assimp/assimp/tree/feature/configured_precision

Any plan to merge this to master - seems like a pretty solid contribution and opt-in for anyone who doesn't need it.

**Comment by r-chris** [comment]
I rebased that branch to master, but not sure if there are many outstanding fixes to be done since float is still used in many instances:
https://github.com/r-chris/assimp/tree/configured_precision

My actual problem here is with the export, though - I currently see all exported values written like this:

```
v  557760 4.07449e+06 -49.1995
v  557760 4.07449e+06 -49.095
v  557760 4.0745e+06 -49.0082
v  557760 4.0745e+06 -49.1127
```

It looks like  you are using

```
public:
    std::ostringstream mOutput, mOutputMat;
```

and then something like this (obj example):

```
mOutput << "# " << vp.size() << " vertex positions" << endl;
for(const aiVector3D& v : vp) {
    mOutput << "v  " << v.x << " " << v.y << " " << v.z << endl;
}
mOutput << endl;
```

Apparently, you can technically set the `stringstream` precision to 16 (http://www.cplusplus.com/reference/ios/ios_base/precision/) to get more than 6 digits as output.

I understand that `mOutput` is a public variable, but I am calling `Assimp::Exporter exporter;`, which doesn't expose this to me - it would be great to hear if you have any advice how I should increase the output precision (or will this require source code changes in `assimp`)?

**Comment by r-chris** [comment]
After some digging in the different exporters it appears that some of them already set a higher precision for export, while others don't. I have made this behaviour more consistent and will send a PR #935 your way.

**Comment by r-chris** [comment]
Following up on the double precision support, I initiated a PR #947, which will introduce double precision (optionally) for people, who need more digits at time of export. Please note that this still needs work on the import side!
