### ISSUE TITLE
Add support for PMD & PMX & VMD

### ISSUE THREAD

**Issue by tuxzz** [assimp/assimp#644]
`.pmx` amd `.pmd` are 3d model format, `.vmd` is skeletal animation format.
These formats formats are used in MikuMikuDance and MikuMikuMoving, a software that popular in Vocaloid and Japanese anime fans.

MikuMikuMoving:
https://sites.google.com/site/mikumikumovingeng/

PMX & PMD editor:
http://vadim07.deviantart.com/art/PmxEditor-0222-English-520178628

**Comment by MaddTheSane** [comment]
[This](https://gist.github.com/ulrikdamm/8274171) describes the PMX 2.0 file format.

**Comment by undisputed-seraphim** [comment]
I might take a crack at this, but don't hold your breath.

**Comment by aoowweenn** [comment]
[Update](https://github.com/aoowweenn/assimp/tree/umw_dev)
Now we can establish the armature hierarchy and assign bone weights to vertices.
While current DAE exporter is lack of "vertex_weights" tag, I can't verify the weights.

Next step I think is to jump to VMD importer and use Urho3D to verify the weights.

**Comment by kimkulling** [comment]
What about preparing a pull request. We could mark it as experimental.

**Comment by undisputed-seraphim** [comment]
Just pulled v4.0.1. Glad to see that someone worked on this!

I just have a teeny problem: Build fails spectacularly on Visual Studio, due to the Japanese comments in the source files. After stripping out the characters, it builds successfully.

So, what do the maintainers want to do? I don't mind replacing the Japanese comments with English translations if there's any interest, or just strip them out since most of the comments are just explanations of variable names for the Japanese audience.

**Comment by kimkulling** [comment]
I guess a first step would be to temoce these comments.

Tan Li Boon <notifications@github.com> schrieb am So., 6. Aug. 2017, 17:34:

**Comment by HTTdesu** [comment]
Thank you for adding pmx format parser. But I do find some problems in use.

1. File MMDPmxParser.cpp is not using Unicode, and this really caused me a lot of trouble. An interesting thing is that it can still pass the code check but cannot work correctly since line 521.
`stream->read((char*) &version, sizeof(float));`
The `std::istream` cannot read data into `pmx::Model::version` correctly so it will be 0 and then throw an exception.
Please save it in Unicode.

2. Unexpected problems happen in memory recovery process.
`const aiScene* scene = importer.ReadFile(path, aiProcess_Triangulate | aiProcess_FlipUVs | aiProcess_CalcTangentSpace);`
I'm using such code to load a pmx file into the memory, and this causes a strange exception. When I add a `return` after it, I will got an exception. I guess that this is caused by `destructor` because when I check the call stack I also find three functions, which are declared in `assimp.dll`, are used in this `return` sentence.
I'm now working on it.

3. UTF-16(LE) to UTF-8 encoder actually cannot work. (File MMDPmxParser.cpp Line 92)

**Comment by aoowweenn** [comment]
Thank you to point out these problems.
Sorry for almost a year delay,

1. There are still some Japanese comment out ther.
It should be a quick fix.

I think (2) and (3) may be caused by (1)?

**Comment by HTTdesu** [comment]
Unfortunately, they are not :(
For problem 2, I use PmxEditor(ver. 0222) to change the pmx file from UTF-16 to UTF-8 to avoid this problem. Now I'm not using the encoder :)
For problem 3, I finally find out that it was really caused by the `destructor` in File Version.cpp line 146.
<pre>if (mNumMeshes && mMeshes)
	for (unsigned int a = 0; a < mNumMeshes; a++)
		delete mMeshes[a]; // This line
	delete [] mMeshes;</pre>
It seems that mMeshes[a] is already `null` before `delete`. I temporarily add an `if` to fix this problem.
<pre>if (mNumMeshes && mMeshes)
	for (unsigned int a = 0; a < mNumMeshes; a++)
		if(!mMeshes[a])
			delete mMeshes[a];
	delete [] mMeshes;</pre>
Now it works correctly.
Please check MMDPmxParser.cpp to fix this problem because I don't think changing Assimp's own file instead of a parser can be a good solution.

**Comment by HTTdesu** [comment]
This time I think that I DO find a bug for you :)
It is in `MMDPmxParser.cpp` Line 102, the utf-16 to utf-8 encoder which I have complained about before.

I got the function prototype and write it here:
<pre>template &lt;typename u16bit_iterator, typename octet_iterator&gt;
octet_iterator utf16to8 (u16bit_iterator start, u16bit_iterator end, octet_iterator result)
{
    while (start != end)
    {
        uint32_t cp = utf8::internal::mask16(*start++);
        ...... //omitted
        result = utf8::append(cp, result);
    }
    return result;
}
</pre>
We can easily point out that the function uses `start++` to iterate each utf-16 characters.

But this function is called by `utf8::utf16to8( sourceStart, sourceStart + size, targetStart );`, here the type of `sourceStart` is `const char*`, so the loop will actually runs "size" times, while we know that it should only runs half as many as it. (Each utf-16 character cost 2 bytes)

I fixed it by `utf8::utf16to8( (uint16_t*)sourceStart, (uint16_t*)sourceStart + size / 2, targetStart );`

Also, several lines later, `result.assign(targetReserved, targetStart - targetReserved);`
Here `utf16to8` does not change `targetStart`, so the second parameter is always 0, which makes `result` a blank string. Simply uses `return std::string(targetStart);` can solve the problem. If you do so, you also need to initialize `targetStart`.

**Comment by aoowweenn** [comment]
Oh, the utf8 library in assimp now is different from the version I met last year.
Thanks, and I fixed it in my [branch](https://github.com/aoowweenn/assimp)
While the null problem of mMeshes[a] is still not solved,
I have observed some models failed to load, and maybe related to it.
Just wait to see if I have time to debug it.

**Comment by HTTdesu** [comment]
Well, I agree with you. But I removed "!" just now and got an exception, so I have to put it back.  I don't know why. It seems that I released something wrong?
One guess is that `unique_ptr` may destroy itself before we `delete` it.
As a Java programmer, I'm not so familiar with C++ libraries :(

EVERY model I tried failed last month, that's why I started debugging. Including YYB_Miku_10th, YYB_ene and several other YYB style models. Only pmx models failed. obj and fbx models were fine.

**Comment by kismeter** [comment]
I have a problem when porting assimp to android. MMD PMX file is located at Android Asset, when load the PMX file always show the file can't load "Failed to open file xxx.pmx. maybe there's a bug on InternReadFile

```
//  MMD import implementation
void MMDImporter::InternReadFile(const std::string &file, aiScene *pScene,
                                 IOSystem * /*pIOHandler*/) {
  // Read file by istream
  std::filebuf fb;
  if (!fb.open(file, std::ios::in | std::ios::binary)) {
    throw DeadlyImportError("Failed to open file " + file + ".");
  }

  std::istream fileStream(&fb);

  // Get the file-size and validate it, throwing an exception when fails
  fileStream.seekg(0, fileStream.end);
  size_t fileSize = static_cast<size_t>(fileStream.tellg());
  fileStream.seekg(0, fileStream.beg);

  if (fileSize < sizeof(pmx::PmxModel)) {
    throw DeadlyImportError(file + " is too small.");
  }

  pmx::PmxModel model;
  model.Read(&fileStream);

  CreateDataFromImport(&model, pScene);
}
```

**Comment by fire** [comment]
Current godot master https://github.com/godotengine/godot/commit/24e1039eb6fe32115e8d1a62a84965e9be19a2ed has an implementation for pmx importing.

![editor_screenshot_2019-09-10T190817-0700](https://user-images.githubusercontent.com/32321/64662782-7d5e5980-d3fe-11e9-9f5e-dd0a31811fad.png)

I've interested in vmd importing, but I don't know where to start.

https://github.com/benikabocha/saba Saba is a complete sample implementation under MIT license.

**Comment by HTTdesu** [comment]
Well, actually, there IS a VMD parser in Assimp, but it's just ignored. A `.h` file named `MMDVmdParser.h` is available in `code/MMD` directory. Although comments are missing, the code can explain itself quite clearly. If you are interested in parsing VMD, you shouldn't miss it.

P.S. An important thing is that, character encoding is different in model and action files. The basic approach of matching bones in PMX files and VMD files is to compare their names. However, bone names in PMX files are encoded in `UTF-16`, whereas those in VMD files are encoded in `SHIFT-JIS`. So maybe you need to take a look at `libiconv`.

**Comment by fire** [comment]
I don't know if this is the right approach, but I was able to get the converted data structures from saba. 

My conversion isn't complete, but I can get the vmd motion data which has skeletal, ik and morph controllers.

https://github.com/fire/godot/blob/36f789e97601b51a80b6a1bac0421f061bfa2fb7/thirdparty/assimp/code/MMD/VMDImporter.cpp#L83

I don't think the vmd parser is able to read file in assimp.

The dependencies are glm, spdlog. The related https://github.com/fire/godot/blob/36f789e97601b51a80b6a1bac0421f061bfa2fb7/thirdparty/saba-mmd/Saba/Base/UnicodeUtil.cpp is how saba does unicode conversion.

**Comment by fire** [comment]
My plan is to develop the vmd conversion animation code and then use the saba library for mmd import.

**Comment by Elmapul** [comment]
> Current godot master [godotengine/godot@24e1039](https://github.com/godotengine/godot/commit/24e1039eb6fe32115e8d1a62a84965e9be19a2ed) has an implementation for pmx importing.
> 
> ![editor_screenshot_2019-09-10T190817-0700](https://user-images.githubusercontent.com/32321/64662782-7d5e5980-d3fe-11e9-9f5e-dd0a31811fad.png)
> 
> I've interested in vmd importing, but I don't know where to start.
> 
> https://github.com/benikabocha/saba Saba is a complete sample implementation under MIT license.
> 
> Edited:
> 
> https://twitter.com/2mk_km2/status/1170821452779544576?s=20
> 
> The twitter has a link to the PMX and the VMD.
> 
> This is PMX in Godot Engine with Assimp.

that branch was 3.2 or godot 4?

**Comment by fire** [comment]
At some point, it was removed before 3.2 was launched.

I'll try to see if I can get 3.2's gltf2 blender exporter to work.

Will report back.

**Comment by fire** [comment]
Used https://github.com/powroupi/blender_mmd_tools.

Afterwards, download that vmd and pmx combination.

Exported to gltf2 using Blender glTF io master https://github.com/KhronosGroup/glTF-Blender-IO .

Load PMX. (Translate names here in importer, order of operation matters.) Load VMD. Auto pack blend. Join meshes. Repeated (Use gltf2 from blender gltf2 master). Then export. I think apply modifiers needs to be enabled.

Materials are broken.

https://www.youtube.com/watch?v=W4JKGfWH-k4

**Comment by Quanfita** [comment]
Is pyassimp support PMX format now? When I load a PMX file, it takes me an error. 
pyassimp.errors.AssimpError: Could not import file!

**Comment by neo-mashiro** [comment]
Do we have support for loading VMD animations now? I saw there's a VMD parser in https://github.com/assimp/assimp/tree/master/code/AssetLib/MMD but seems like it's not being used. Or does anyone know any VMD convertion tools? I tried to import PMX model into Blender 2.90 and apply VMD motions but it only works there, as soon as I exported them to one FBX everything is broken

**Comment by Elmapul** [comment]
> Do we have support for loading VMD animations now? I saw there's a VMD parser in https://github.com/assimp/assimp/tree/master/code/AssetLib/MMD but seems like it's not being used. Or does anyone know any VMD convertion tools? I tried to import PMX model into Blender 2.90 and apply VMD motions but it only works there, as soon as I exported them to one FBX everything is broken

i think this is the most updated MMD importer:
https://github.com/UuuNyaa/blender_mmd_tools

i dont know if its perfect yet (or if it will ever be).
once its imported to bender you can export to gltf wich should work in any modern program.
let then know if you strugle to import anything. (if you find any model that it cant import)

**Comment by aoowweenn** [comment]
@neo-mashiro
Appreciate to hear from your demand for VMD support.
I think currently assimp is hard to fully fit with MMD formats,
even though assimp is really a common model I/O loader/converter.

As @Elmapul pointed out,
please stick with the latest blender add-on for now,
https://github.com/UuuNyaa/blender_mmd_tools/tree/main
and the state-of-the-art viewer
https://github.com/benikabocha/saba

I'm quite busy these years but still look forward to the promising future of MMD.
If I have further free time, some critical contributions will be considered to be made.
