### ISSUE TITLE
Problem linking against master

### ISSUE THREAD

**Issue by TurkeyMan** [assimp/assimp#687]
Linking against a build from master, I get this error:
```
undefined reference to `Assimp::Importer::SetPropertyInteger(char const*, int, bool*)
```

Built the v3.1.1 tag instead and it works fine.

Maybe a user error, I didn't dig any further than this.

**Comment by TurkeyMan** [comment]
Build was linux x86_64

**Comment by kimkulling** [comment]
Sounds crazy. I will try to reproduce this issue. Thanks for reporting it!

**Comment by OtgerRP** [comment]
If it is any help, I got this error when I compiled the library from master, because the project that used it had the assimp "include" folder for an older version (specifically the one from the SourceForge  3.1.1 download).

It seems the function lost its third parameter in the recent versions, so the library exports a function with 2 and the headers expected one with 3.

**Comment by kimkulling** [comment]
Good point, which include folder is in use on your side?

**Comment by kimkulling** [comment]
Any updates?

**Comment by haikarainen** [comment]
I got the same issue as otgerrogla had. Used official fedora packages for assimp previously, then built my own (for FBX support) and forgot to remove the package before doing make install.

I think it's safe to say that this is user error and that this issue can be closed.

**Comment by kimkulling** [comment]
Ok, I will close the isse though. if you still have any issues feel free to reopen it.
