### ISSUE TITLE
Story: improve the base performance

### ISSUE THREAD

**Issue by kimkulling** [assimp/assimp#767]
Just a high-level story to collct some ideas how to improve the performance. So what can we do
- Performance tests
- Identify hot spots
- Improve them

**Comment by sherief** [comment]
Step 1: profile? 

We need a set of large test files, in every supported format, and some automated test that times import / export to these formats. Some fixes will affect more than one format, so that's nice, but we really need this repo of large files at least. Small files, in my experience, are good at hiding the real hotspots in the code.
