### ISSUE TITLE
FBX & Camera broken

### ISSUE THREAD

**Issue by vd3d** [assimp/assimp#807]
Hi,

It seems that importing the camera with FBX is broken. I'm not the first one to notice this problem but they don't got any feedback (https://github.com/assimp/assimp/issues/643).

Does someone has some news about this problem ?

Thanks

**Comment by vd3d** [comment]
Here is my code : http://stackoverflow.com/questions/35536994/assimp-import-camera

**Comment by kimkulling** [comment]
Hi,

sorry for the delay. Trying to get some knowledge about this format. 

Kimmi

**Comment by kimkulling** [comment]
I just checked the model from #643. Camera position is on the wrong side of the scene. And there is another camera in the scene, which was not parsed at all. I am still investigating this issue. At the moment I trying to get the right transformation of the camera via blender.

**Comment by kimkulling** [comment]
Ok, after parsing with Assimp the camera from untitled.fbx contains a data definition for transform x = 1207 instead of 12.07 checked in Blender. Z differs also about factor 10. Y seems to be wrong. Any ideas where these factor comes from? I checked the model from #643. 
and forget what I said about a second camera: it was the default camera from blender which I saw in blender, but not in the model.
