### ISSUE TITLE
FBX import assert failed

### ISSUE THREAD

**Issue by fredrik955** [assimp/assimp#811]
/assimp/code/FBXDocument.h:863: const unsigned int\* Assimp::FBX::MeshGeometry::ToOutputVertexIndex(unsigned int, unsigned int&) const: Assertion `count != 0' failed.

Failed model:
https://storage.googleapis.com/assimp_model_error/FBX_assert_failed.fbx

**Comment by kimkulling** [comment]
I can reproduce the issue. The fbx-importer is using a lookup table to see if a vertex is in use. IN your crash this lookup value is 0 and an assertion brings down your application.
Unfortunately I do not have a clue at the moment why this is happening.

**Comment by thloh85** [comment]
This happens when you have a lot of quads instead of triangles (I don't know how many) in your FBX and enable the triangulate option when you load the model in Assimp. I don't have the fix for this, but I guess this helps to debug the issue. I can workaround this by triangulate when exporting to FBX before importing in Assimp.

**Comment by kimkulling** [comment]
Just an update from myself: I didn't had time to do some investigations. But I am still optimistic to work on a fix for you!

**Comment by kimkulling** [comment]
I guess I was much too much optimistic. I cannot download the model. So I will close the issue. If this one is still an issue just reopen it.
