### ISSUE TITLE
Materials lost on import

### ISSUE THREAD

**Issue by mraof** [assimp/assimp#895]
When I import an OBJ or OpenGEX model, the materials are lost. In the case of the OpenGEX file, only the IndexArray in the mesh using the last material is kept.
The files I tested this with (Same model, both exported from blender originally) and the files I get exporting both as OBJ: [https://gist.github.com/mraof/c8764e6f70bfe0870a2cafc5f4a31c61](https://gist.github.com/mraof/c8764e6f70bfe0870a2cafc5f4a31c61)

**Comment by kimkulling** [comment]
The gist-link is dead. Do you have another example to reproduce the issue?

**Comment by mraof** [comment]
I fixed the gist link, sorry about that

**Comment by kimkulling** [comment]
Could you please upload a zip-archive with all these models. Hard to get them this way. Thanks a lot!

**Comment by JasonWinston** [comment]
I do not know the use of "mColors" of a aiMesh.Who can tell me about it?

**Comment by mraof** [comment]
Sure, here's a zip
[c8764e6f70bfe0870a2cafc5f4a31c61-e1e7bc8bb002d43b8fadebbdf5244e8c92f60f6d.zip](https://github.com/assimp/assimp/files/275920/c8764e6f70bfe0870a2cafc5f4a31c61-e1e7bc8bb002d43b8fadebbdf5244e8c92f60f6d.zip)

**Comment by jeannekamikaze** [comment]
I am observing a similar issue here, please refer to the model file linked below [1].

Attached is an OBJ file with its corresponding MTL file. The OBJ file defines a single object that uses the one and only material defined in the MTL file. The material in the MTL file then defines the usual phong model variables and references the file debug-64.png as the diffuse texture. With assimp 3.3.1 taken from the Ubuntu repos, I am observing the following:

- If I load the scene with flag aiProcess_RemoveRedundantMaterials, the scene is loaded with 1 material but that material has no diffuse texture (the diffuse texture debug-64.png is lost).
- If I drop the aiProcess_RemoveRedundantMaterials flag, the scene loads with 2 materials. The first material has no diffuse texture, and the second material has debug-64.png as the diffuse texture.

My expectations:

- Regardless of whether I pass the aiProcess_RemoveRedundantMaterials flag, since the OBJ and MTL files are as simple as it gets, assimp should load the scene with 1 material and that material should have debug-64.png as the diffuse texture.

These are all the flags I am passing to assimp when loading the scene:

```
const aiScene* scene = importer.ReadFile(path,
            aiProcess_Triangulate |
            aiProcess_GenSmoothNormals |
            aiProcess_FixInfacingNormals |
            aiProcess_JoinIdenticalVertices |
            aiProcess_PreTransformVertices |
            //aiProcess_RemoveRedundantMaterials |
            aiProcess_SortByPType |
            aiProcess_ImproveCacheLocality |
            aiProcess_OptimizeMeshes);
```

Please let me know if you need any other piece of information.

Thanks.

[1] https://www.dropbox.com/s/c0ztjj9krlcm0jb/model.7z?dl=0

**Comment by kimkulling** [comment]
IN the supported file the referenced material is missing. And that seems to be the reason for the vanished material.
