### ISSUE TITLE
Material shininess value scale is dependant on input format

### ISSUE THREAD

**Issue by jpx** [assimp/assimp#968]
Depending on the imported format, shininess value read from material might be either scaled or remain unchanged. When a scale is applied, it also depends on imported format.

For instance, shininess ranges between following values for formats
- FBX -> scaled [0,100]
- OBJ -> scaled [0, 4000]
- DAE -> untouched (Blender range is [0, 511])

Ideally, the retrieved shininess should always be scaled by Assimp based on format to provide a **unique  scale** (for instance between [0.0, 1.0]).

Samples allowing to find those values were exported with Blender 2.77 and can be found [here](https://drive.google.com/file/d/0B-A32fKlVI01OUVIOTg2WFoyS2s/view?usp=sharing.)

Related to #841 and #123.

**Comment by kimkulling** [comment]
Ops, thanks for the report. Wenn will take Carey!

jpx <notifications@github.com> schrieb am Mo., 8. Aug. 2016, 19:32:

**Comment by promethe42** [comment]
> Ideally, the retrieved shininess should always be scaled by Assimp based on format to provide a unique scale (for instance between [0.0, 1.0]).

Ideally, those values should actually be untouched.

Normalization should apply only when the scale/unit is actually different, not because different editors provide different min/max values. For example, the fact that Blender cannot have a shininess > 511 does not mean that it doesn't have the propre "shininess" semantics and that it is not a propre shininess exponent that can be used in a Phong equation. But if other editors have a shiniess between 0 and 1, like a percentage, then we have a problem and we should normalize.

The thing is we probably don't know from what editor the file comes from... so in the end, maybe this value should be left untouched ? Maybe we should have an ASSIMP option to specify whether it should be normalized?

Regards,

**Comment by JohanJons** [comment]
Would love for shinines to be normalized. Currently the value range varies wildly making it difficult to parse correctly :(

**Comment by kimkulling** [comment]
I guess making this configurable is the war to go.

JohanJons <notifications@github.com> schrieb am Di., 30. Aug. 2016, 00:38:

**Comment by kimkulling** [comment]
Closed by 56e9bce
