### ISSUE TITLE
No data remains on a valid OBJ file

### ISSUE THREAD

**Issue by fredrik955** [assimp/assimp#982]
Hi,

Tried to import this model: [https://storage.googleapis.com/assimp_model_error/no_data_remains_3.obj](https://storage.googleapis.com/assimp_model_error/no_data_remains_3.obj)

But it failed with this message:
`After optimizing the scene graph, no data remains`

I am using these import options:
`importer.SetPropertyFloat(AI_CONFIG_PP_GSN_MAX_SMOOTHING_ANGLE, 45.0f);
importer.SetPropertyInteger(AI_CONFIG_PP_SBP_REMOVE, aiPrimitiveType_LINE | aiPrimitiveType_POINT); //SET THIS TO REMOVE POINTS AND LINES -> HAVE ONLY TRIANGLES
scene = importer.ReadFile(
  filename,
  aiProcess_Triangulate           |
  aiProcess_GenUVCoords           |
  aiProcess_GenSmoothNormals      |
  aiProcess_OptimizeMeshes        |
  aiProcess_OptimizeGraph         |
  aiProcess_FixInfacingNormals    |
  aiProcess_JoinIdenticalVertices |
  aiProcess_SortByPType
);
`

**Comment by Sailsman63** [comment]
What programs does this model work properly with?

I've tried loading it in three different apps now, 

 - Meshlab won't load the file, says "No vertex found"
 - Microsoft 3d Builder also refuses to load the file, with an opaque error code.
 - ArtOfIllusion, a modeling/animation package, will load the file, but the resulting mesh has issues. Some of the (limited) diagnostics I have been able to run, the resulting triangulated mesh has a pair of exactly coincident faces with reversed normals.

Are you trying to remove points and lines because you software does not support them, or because you prefer not to have them in this mesh? Per the postprocess.h documentation regarding the ai_findDegenerates, which handles the flag AI_CONFIG_PP_SBP_REMOVE:

>Degenerate polygons are not necessarily evil and that's why they're not removed by default. There are several file formats which don't support lines or points, and some exporters bypass the format specification and write them as degenerate triangles instead.

**Comment by fredrik955** [comment]
Hi @Sailsman63,

I got this file from a user and don't know which program this file was meant for. I will ask to figure it out.

Yes, I enabled AI_CONFIG_PP_SBP_REMOVE because our software don't support point and lines. Yes, I see the problem with degenerated triangles.

**Comment by kimkulling** [comment]
You can check the log for the number of degerneated triangles as well.
